// Source: Web Animations (https://www.w3.org/TR/web-animations-1/)
[Exposed=Window]
interface AnimationTimeline {
    readonly attribute double? currentTime;
    readonly attribute TimelinePhase phase;
};

// Source: Web Animations Level 2 (https://drafts.csswg.org/web-animations-2/)
[Exposed=Window]
partial interface AnimationTimeline {
    readonly attribute CSSNumberish? duration;
    Animation play (optional AnimationEffect? effect = null);
};