// Source: App History API (https://wicg.github.io/app-history/)
[Exposed=Window]
interface AppHistoryTransition {
  readonly attribute AppHistoryNavigationType navigationType;
  readonly attribute AppHistoryEntry from;
  readonly attribute Promise<undefined> finished;

  Promise<undefined> rollback(optional AppHistoryNavigationOptions options = {});
};