// Source: WebCodecs (https://w3c.github.io/webcodecs/)
dictionary AudioDecoderConfig {
  required DOMString codec;
  required unsigned long sampleRate;
  required unsigned long numberOfChannels;
  BufferSource description;
};