// Source: Web Authentication: An API for accessing Public Key Credentials - Level 2 (https://www.w3.org/TR/webauthn-2/)
dictionary AuthenticationExtensionsClientInputs {
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 2 (https://www.w3.org/TR/webauthn-2/)
partial dictionary AuthenticationExtensionsClientInputs {
  USVString appid;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 2 (https://www.w3.org/TR/webauthn-2/)
partial dictionary AuthenticationExtensionsClientInputs {
  USVString appidExclude;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 2 (https://www.w3.org/TR/webauthn-2/)
partial dictionary AuthenticationExtensionsClientInputs {
  boolean uvm;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 2 (https://www.w3.org/TR/webauthn-2/)
partial dictionary AuthenticationExtensionsClientInputs {
    boolean credProps;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 2 (https://www.w3.org/TR/webauthn-2/)
partial dictionary AuthenticationExtensionsClientInputs {
    AuthenticationExtensionsLargeBlobInputs largeBlob;
};