// Source: Web Authentication: An API for accessing Public Key Credentials - Level 2 (https://www.w3.org/TR/webauthn-2/)
[SecureContext, Exposed=Window]
interface AuthenticatorResponse {
    [SameObject] readonly attribute ArrayBuffer      clientDataJSON;
};