// Source: Payment Method: Basic Card (https://www.w3.org/TR/payment-method-basic-card/)
dictionary BasicCardResponse {
  required DOMString cardNumber;
  DOMString cardholderName = "";
  DOMString cardSecurityCode = "";
  DOMString expiryMonth = "";
  DOMString expiryYear = "";
  PaymentAddress? billingAddress = null;
};