// Source: WebTransport (https://www.w3.org/TR/webtransport/)
interface mixin BidirectionalStreamsTransport {
    Promise<BidirectionalStream> createBidirectionalStream();
    /* a ReadableStream of BidirectionalStream objects */
    readonly attribute ReadableStream incomingBidirectionalStreams;
};