// Source: WebTransport (https://www.w3.org/TR/webtransport/)
[ Exposed=(Window,Worker) ]
interface BidirectionalStream {
  readonly attribute ReceiveStream readable;
  readonly attribute SendStream writable;
};