// Source: WebTransport (https://w3c.github.io/webtransport/)
[ Exposed=(Window,Worker) ]
interface BidirectionalStream {
};

// Source: WebTransport (https://w3c.github.io/webtransport/)
BidirectionalStream includes OutgoingStream;

// Source: WebTransport (https://w3c.github.io/webtransport/)
BidirectionalStream includes IncomingStream;