// Source: Capture Handle - Bootstrapping Collaboration when Screensharing (https://w3c.github.io/mediacapture-handle/identity/)
[Exposed=Window]
interface CaptureHandleChangeEvent : Event {
  constructor(optional CaptureHandleChangeEventInit init = {});
  [SameObject] CaptureHandle captureHandle();
};