// Source: Service Workers 1 (https://www.w3.org/TR/service-workers-1/)
[Exposed=ServiceWorker]
interface Client {
  readonly attribute USVString url;
  readonly attribute FrameType frameType;
  readonly attribute DOMString id;
  readonly attribute ClientType type;
  void postMessage(any message, optional sequence<object> transfer = []);
};

// Source: Page Lifecycle (https://wicg.github.io/page-lifecycle/)
partial interface Client {
    readonly attribute ClientLifecycleState lifecycleState;
};