// Source: Close Watcher API (https://wicg.github.io/close-watcher/)
[Exposed=Window]
interface CloseWatcher : EventTarget {
  constructor();

  undefined destroy();
  undefined signalClose();

  attribute EventHandler onclose;
};