// Source: Compute Pressure API (https://wicg.github.io/compute-pressure/)
dictionary ComputePressureObserverUpdate {
  double cpuSpeed;
  double cpuUtilization;
  ComputePressureObserverOptions options;
};