// Source: Compute Pressure API (https://wicg.github.io/compute-pressure/)
[Exposed=(DedicatedWorker,SharedWorker,Window), SecureContext]
interface ComputePressureObserver {
  constructor(ComputePressureUpdateCallback callback, optional ComputePressureObserverOptions options = {});

  undefined observe(ComputePressureSource source);
  undefined unobserve(ComputePressureSource source);
  undefined disconnect();
  sequence<ComputePressureRecord> takeRecords();

  [SameObject] static readonly attribute FrozenArray<ComputePressureSource> supportedSources;

  [Exposed=Window] static Promise<PermissionState> requestPermission();
};