// Source: Compute Pressure API Level 1 (https://wicg.github.io/compute-pressure/)
callback ComputePressureUpdateCallback = undefined (
  sequence<ComputePressureRecord> changes,
  ComputePressureObserver observer
);