// Source: Compute Pressure API (https://wicg.github.io/compute-pressure/)
callback ComputePressureUpdateCallback = undefined (
  ComputePressureObserverUpdate update,
  ComputePressureObserver observer
);