// Source: Compute Pressure API (https://wicg.github.io/compute-pressure/)
dictionary ComputePressureObserverOptions {
  sequence<double> cpuUtilizationThresholds = [];
  sequence<double> cpuSpeedThresholds = [];
};