// Source: CSS Fonts Module Level 4 (https://www.w3.org/TR/css-fonts-4/)
[Exposed=Window]
interface CSSFontPaletteValuesRule : CSSRule {
  maplike<unsigned long, CSSOMString>;
  attribute CSSOMString fontFamily;
  attribute CSSOMString basePalette;
};