// Source: Constructable Stylesheet Objects (https://wicg.github.io/construct-stylesheets/)
dictionary CSSStyleSheetInit {
  (MediaList or DOMString) media = "";
  DOMString title = "";
  boolean alternate = false;
  boolean disabled = false;
};