// Source: WebTransport (https://www.w3.org/TR/webtransport/)
interface mixin DatagramTransport {
    readonly attribute unsigned short maxDatagramSize;
    readonly attribute DatagramDuplexStream datagrams;
};