// Source: WebTransport (https://w3c.github.io/webtransport/)
interface mixin DatagramTransport {
    readonly attribute unsigned short maxDatagramSize;
    readonly attribute DatagramDuplexStream datagrams;
};