// Source: Media Capture Depth Stream Extensions (https://www.w3.org/TR/mediacapture-depth/)
dictionary DistortionCoefficients {
    double k1;
    double k2;
    double p1;
    double p2;
    double k3;
};