// Source: WebCodecs (https://wicg.github.io/web-codecs/)
dictionary EncodedAudioChunkInit {
  required EncodedAudioChunkType type;
  required unsigned long long timestamp;
  required BufferSource data;
};