// Source: Web App Manifest (https://www.w3.org/TR/appmanifest/)
dictionary ExternalApplicationResource {
  required USVString platform;
  USVString url;
  DOMString id;
  USVString min_version;
  sequence<Fingerprint> fingerprints;
};