// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
dictionary FederatedCredentialRequestOptions {
  sequence<USVString> providers;
  sequence<DOMString> protocols;
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
partial dictionary FederatedCredentialRequestOptions {
  sequence<(DOMString or FederatedIdentityProvider)> providers;
};