// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
[Constructor(FederatedCredentialInit data),
 Exposed=Window,
 SecureContext]
interface FederatedCredential : Credential {
  readonly attribute USVString provider;
  readonly attribute DOMString? protocol;
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
FederatedCredential includes CredentialUserData;