// Source: WebAssembly JavaScript Interface (https://www.w3.org/TR/wasm-js-api-1/)
[LegacyNamespace=WebAssembly, Constructor(GlobalDescriptor descriptor, optional any v), Exposed=(Window,Worker,Worklet)]
interface Global {
  any valueOf();
  attribute any value;
};