// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker)]
interface GPUBindGroupLayout {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUBindGroupLayout includes GPUObjectBase;