// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker), SecureContext]
interface GPUComputePassEncoder {
    undefined setPipeline(GPUComputePipeline pipeline);
    undefined dispatch(GPUSize32 x, optional GPUSize32 y = 1, optional GPUSize32 z = 1);
    undefined dispatchIndirect(GPUBuffer indirectBuffer, GPUSize64 indirectOffset);

    undefined endPass();
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePassEncoder includes GPUObjectBase;

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePassEncoder includes GPUCommandsMixin;

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePassEncoder includes GPUDebugCommandsMixin;

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePassEncoder includes GPUProgrammablePassEncoder;