// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
[Exposed=Window, Serializable]
interface GPUComputePipeline {
};

// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
GPUComputePipeline includes GPUObjectBase;

// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
GPUComputePipeline includes GPUPipelineBase;