// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=Window]
interface GPUCommandBuffer {
    readonly attribute Promise<double> executionTime;
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUCommandBuffer includes GPUObjectBase;