// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
[Exposed=Window]
interface GPUDeviceLostInfo {
    readonly attribute (GPUDeviceLostReason or undefined) reason;
    readonly attribute DOMString message;
};