// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
dictionary GPUExtent3DDict {
    GPUIntegerCoordinate width = 1;
    GPUIntegerCoordinate height = 1;
    GPUIntegerCoordinate depthOrArrayLayers = 1;
};