// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
[Serializable]
interface GPURenderPipeline {
};

// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
GPURenderPipeline includes GPUObjectBase;

// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
GPURenderPipeline includes GPUPipelineBase;