// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
[Exposed=Window]
interface GPUSwapChain {
    GPUTexture getCurrentTexture();
};

// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
GPUSwapChain includes GPUObjectBase;