// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=Window]
interface GPUSwapChain {
    GPUTexture getCurrentTexture();
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUSwapChain includes GPUObjectBase;