// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
[Serializable]
interface GPUShaderModule {
    Promise<GPUCompilationInfo> compilationInfo();
};

// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
GPUShaderModule includes GPUObjectBase;