// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker)]
interface GPUShaderModule {
    Promise<GPUCompilationInfo> compilationInfo();
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUShaderModule includes GPUObjectBase;