// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=Window, Serializable]
interface GPUShaderModule {
    Promise<GPUCompilationInfo> compilationInfo();
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUShaderModule includes GPUObjectBase;