// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
[Exposed=Window, Serializable]
interface GPUTexture {
    GPUTextureView createView(optional GPUTextureViewDescriptor descriptor = {});

    undefined destroy();
};

// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
GPUTexture includes GPUObjectBase;