// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface HTMLScriptElement : HTMLElement {
  [HTMLConstructor] constructor();

  [CEReactions] attribute USVString src;
  [CEReactions] attribute DOMString type;
  [CEReactions] attribute boolean noModule;
  [CEReactions] attribute boolean async;
  [CEReactions] attribute boolean defer;
  [CEReactions] attribute DOMString? crossOrigin;
  [CEReactions] attribute DOMString text;
  [CEReactions] attribute DOMString integrity;
  [CEReactions] attribute DOMString referrerPolicy;

  static boolean supports(DOMString type);

  // also has obsolete members
};

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
partial interface HTMLScriptElement {
  [CEReactions] attribute DOMString charset;
  [CEReactions] attribute DOMString event;
  [CEReactions] attribute DOMString htmlFor;
};

// Source: Subresource Integrity (https://www.w3.org/TR/SRI/)
partial interface HTMLScriptElement {
                    attribute DOMString integrity;
};