// Source: Indexed Database API 2.0 (https://www.w3.org/TR/IndexedDB-2/)
dictionary IDBVersionChangeEventInit : EventInit {
  unsigned long long oldVersion = 0;
  unsigned long long? newVersion = null;
};