// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
interface IdentityCredential : Credential {
  readonly attribute USVString? idToken;
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface IdentityCredential {
  static Promise<undefined> logoutRPs(sequence<IdentityCredentialLogoutRpsRequest> logoutRequests);
};