// Source: Cooperative Scheduling of Background Tasks (https://www.w3.org/TR/requestidlecallback/)
interface IdleDeadline {
    DOMHighResTimeStamp timeRemaining();
    readonly attribute boolean didTimeout;
};