// Source: Web Animations (https://www.w3.org/TR/web-animations-1/)
dictionary KeyframeEffectOptions : EffectTiming {
    IterationCompositeOperation iterationComposite = "replace";
    CompositeOperation          composite = "replace";
};