// Source: MathML Core (https://w3c.github.io/mathml-core/)
[Exposed=Window]
interface MathMLElement : Element { };

// Source: MathML Core (https://w3c.github.io/mathml-core/)
MathMLElement includes GlobalEventHandlers;

// Source: MathML Core (https://w3c.github.io/mathml-core/)
MathMLElement includes DocumentAndElementEventHandlers;

// Source: MathML Core (https://w3c.github.io/mathml-core/)
MathMLElement includes HTMLOrForeignElement;