// Source: "MediaStream Image Capture" (https://www.w3.org/TR/image-capture/)
interface MediaSettingsRange {
    readonly attribute double max;
    readonly attribute double min;
    readonly attribute double step;
};