// Source: Media Session Standard (https://www.w3.org/TR/mediasession/)
[Exposed=Window]
interface MediaSession {
  attribute MediaMetadata? metadata;

  attribute MediaSessionPlaybackState playbackState;

  void setActionHandler(MediaSessionAction action, MediaSessionActionHandler? handler);

  void setPositionState(optional MediaPositionState state = {});
};