// Source: Web MIDI API (https://www.w3.org/TR/webmidi/)
[Constructor(DOMString type, optional MIDIConnectionEventInit eventInitDict)]
interface MIDIConnectionEvent : Event {
    readonly    attribute MIDIPort port;
};