// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface MimeType {
  readonly attribute undefined type;
  readonly attribute undefined description;
  readonly attribute undefined suffixes;
  readonly attribute undefined enabledPlugin;
};