// Source: Device Memory (https://www.w3.org/TR/device-memory-1/)
[
    NoInterfaceObject,
    SecureContext,
    Exposed=(Window,Worker)
] interface NavigatorDeviceClass {
    readonly attribute double deviceMemory;
};