// Source: Navigation API (https://wicg.github.io/navigation-api/)
dictionary NavigationCurrentEntryChangeEventInit : EventInit {
  NavigationNavigationType? navigationType = null;
  required NavigationHistoryEntry destination;
};