// Source: Badging API (https://w3c.github.io/badging/)
// Methods exposed on both documents and service workers.
[SecureContext]
interface mixin NavigatorBadge {
  Promise<undefined> setAppBadge(optional [EnforceRange] unsigned long long contents);
  Promise<undefined> clearAppBadge();
};