// Source: Performance Timeline (https://www.w3.org/TR/performance-timeline-2/)
callback PerformanceObserverCallback = undefined (PerformanceObserverEntryList entries,
                                             PerformanceObserver observer,
                                             optional PerformanceObserverCallbackOptions options = {});