// Source: Performance Timeline Level 2 (https://www.w3.org/TR/performance-timeline-2/)
callback PerformanceObserverCallback = void (PerformanceObserverEntryList entries,
                                             PerformanceObserver observer);