// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary PlaneInit {
  required BufferSource data;
  [EnforceRange] required unsigned long stride;
  [EnforceRange] unsigned long offset = 0;
};