// Source: Geolocation API Specification 2nd Edition (https://www.w3.org/TR/geolocation-API/)
[NoInterfaceObject]
interface Position {
  readonly attribute Coordinates coords;
  readonly attribute DOMTimeStamp timestamp;
};