// Source: WebTransport (https://w3c.github.io/webtransport/)
[ Exposed=(Window,Worker) ]
interface ReceiveStream {
};

// Source: WebTransport (https://w3c.github.io/webtransport/)
ReceiveStream includes IncomingStream;