// Source: WebRTC Insertable Media using Streams (https://w3c.github.io/webrtc-insertable-streams/)
[Exposed=(Window)]
interface RTCRtpScriptTransform {
    constructor(Worker worker, optional object options);
    // FIXME: add messaging methods.
};