// Source: Identifiers for WebRTC's Statistics API (https://www.w3.org/TR/webrtc-stats/)
dictionary RTCSctpTransportStats : RTCStats {
            DOMString transportId;
            double smoothedRoundTripTime;
            unsigned long congestionWindow;
            unsigned long receiverWindow;
            unsigned long mtu;
            unsigned long unackData;
};