// Source: Content Security Policy Level 3 (https://www.w3.org/TR/CSP3/)
[Constructor(DOMString type, optional SecurityPolicyViolationEventInit eventInitDict),
 Exposed=(Window,Worker)]
interface SecurityPolicyViolationEvent : Event {
    readonly    attribute USVString      documentURI;
    readonly    attribute USVString      referrer;
    readonly    attribute USVString      blockedURI;
    readonly    attribute DOMString      violatedDirective;
    readonly    attribute DOMString      effectiveDirective;
    readonly    attribute DOMString      originalPolicy;
    readonly    attribute USVString      sourceFile;
    readonly    attribute DOMString      sample;
    readonly    attribute SecurityPolicyViolationEventDisposition      disposition;
    readonly    attribute unsigned short statusCode;
    readonly    attribute unsigned long  lineNumber;
    readonly    attribute unsigned long  columnNumber;
};