// Source: WebTransport (https://w3c.github.io/webtransport/)
[ Exposed=(Window,Worker) ]
interface SendStream : WritableStream /* of Uint8Array */ {
  readonly attribute Promise<StreamAbortInfo> writingAborted;
  undefined abortWriting(optional StreamAbortInfo abortInfo = {});
};