// Source: WebTransport (https://w3c.github.io/webtransport/)
[ Exposed=(Window,Worker) ]
interface SendStream {
};

// Source: WebTransport (https://w3c.github.io/webtransport/)
SendStream includes OutgoingStream;