// Source: WebRTC Encoded Transform (https://w3c.github.io/webrtc-encoded-transform/)
[Exposed=(Window,DedicatedWorker)]
interface SFrameTransform {
    constructor(optional SFrameTransformOptions options = {});
    Promise<undefined> setEncryptionKey(CryptoKey key, optional CryptoKeyID keyID);
};

// Source: WebRTC Encoded Transform (https://w3c.github.io/webrtc-encoded-transform/)
SFrameTransform includes GenericTransformStream;