// Source: WebRTC Encoded Transform (https://w3c.github.io/webrtc-encoded-transform/)
[Exposed=(Window,DedicatedWorker)]
interface SFrameTransformErrorEvent : Event {
    constructor(DOMString type, SFrameTransformErrorEventInit eventInitDict);

    readonly attribute SFrameTransformErrorEventType type;
    readonly attribute CryptoKeyID? keyID;
    readonly attribute any frame;
};