// Source: WebGL Specification (https://www.khronos.org/registry/webgl/specs/latest/1.0/)
typedef (ImageBitmap or
         ImageData or
         HTMLImageElement or
         HTMLCanvasElement or
         HTMLVideoElement or
         OffscreenCanvas) TexImageSource;