// Source: UI Events (https://www.w3.org/TR/uievents/)
[Constructor(DOMString type, optional UIEventInit eventInitDict), Exposed=Window]
interface UIEvent : Event {
  readonly attribute Window? view;
  readonly attribute long detail;
};

// Source: Input Device Capabilities (https://wicg.github.io/input-device-capabilities/)
partial interface UIEvent {
  readonly attribute InputDeviceCapabilities? sourceCapabilities;
};

// Source: UI Events (https://www.w3.org/TR/uievents/)
partial interface UIEvent {
  // The following support legacy user agents
  readonly attribute unsigned long which;
};