// Source: WebGL EXT_disjoint_timer_query Extension Specification (https://www.khronos.org/registry/webgl/extensions/EXT_disjoint_timer_query/)
[LegacyNoInterfaceObject]
interface WebGLTimerQueryEXT : WebGLObject {
};