// Source: WebGL OES_vertex_array_object Khronos Ratified Extension Specification (https://www.khronos.org/registry/webgl/extensions/OES_vertex_array_object/)
[LegacyNoInterfaceObject]
interface WebGLVertexArrayObjectOES : WebGLObject {
};