// Source: WebXR Hit Test Module (https://immersive-web.github.io/hit-test/)
dictionary XRHitTestOptionsInit {
  required XRSpace space;
  FrozenArray<XRHitTestTrackableType> entityTypes;
  XRRay offsetRay;
};