// Source: WebXR Depth Sensing Module (https://immersive-web.github.io/depth-sensing/)
interface XRWebGLDepthInformation : XRDepthInformation {
  [SameObject] readonly attribute WebGLTexture texture;
};