// Source: Protected Audience (formerly FLEDGE) (https://wicg.github.io/turtledove/)
dictionary AdAuctionDataConfig {
  USVString seller;
  USVString coordinatorOrigin;
  sequence<AdAuctionOneSeller> sellers;

  unsigned long requestSize;
  record<USVString, AdAuctionDataBuyerConfig> perBuyerConfig;
};