// Source: Protected Audience (formerly FLEDGE) (https://wicg.github.io/turtledove/)
dictionary AdAuctionDataConfig {
  required USVString seller;
  required USVString coordinatorOrigin;
  unsigned long requestSize;
  record<USVString, AdAuctionDataBuyerConfig> perBuyerConfig;
};