// Source: Web Animations Module Level 2 (https://www.w3.org/TR/web-animations-2/)
[Exposed=Window]
interface AnimationNodeList {
    readonly attribute unsigned long length;
    getter AnimationEffect? item (unsigned long index);
};