// Source: Animation Triggers (https://drafts.csswg.org/animation-triggers-1/)
[Exposed=Window]
interface AnimationTrigger {
  constructor(optional AnimationTriggerOptions options = {});
  attribute AnimationTimeline timeline;
  attribute AnimationTriggerBehavior behavior;
  attribute any activationRangeStart;
  attribute any activationRangeEnd;
  attribute any activeRangeStart;
  attribute any activeRangeEnd;
};