// Source: Scroll-linked Animations (https://drafts.csswg.org/scroll-animations-1/)
[Exposed=Window]
interface AnimationTimeline {
  readonly attribute CSSNumberish? currentTime;
  CSSNumericValue? getCurrentTime(optional CSSOMString rangeName);
};

// Source: Web Animations Level 2 (https://drafts.csswg.org/web-animations-2/)
[Exposed=Window]
partial interface AnimationTimeline {
    readonly attribute CSSNumberish? duration;
    Animation play (optional AnimationEffect? effect = null);
};