// Source: Attribution Reporting (https://wicg.github.io/conversion-measurement-api/)
dictionary AttributionSourceParams {
  required USVString attributionDestination;
  required DOMString attributionSourceEventId;
  USVString attributionReportTo;
  long long attributionExpiry;
  long long attributionSourcePriority;
};