// Source: Attribution Level 1 (https://www.w3.org/TR/privacy-preserving-attribution/)
dictionary AttributionConversionOptions {
  required USVString aggregationService;
  double epsilon = 1.0;

  required unsigned long histogramSize;

  unsigned long lookbackDays;
  sequence<unsigned long> matchValues = [];
  sequence<USVString> impressionSites = [];
  sequence<USVString> impressionCallers = [];

  AttributionLogic logic = "last-n-touch";
  AttributionLogicOptions logicOptions;
  unsigned long value = 1;
  unsigned long maxValue = 1;
};