// Source: Attribution Reporting (https://wicg.github.io/attribution-reporting-api/)
dictionary AttributionReportingRequestOptions {
  required boolean eventSourceEligible;
  required boolean triggerEligible;
};