// Source: Attribution Level 1 (https://www.w3.org/TR/attribution/)
[SecureContext, Exposed=Window]
interface AttributionAggregationServices {
  readonly maplike<USVString, AttributionAggregationService>;
};