// Source: Protected Audience (formerly FLEDGE) (https://wicg.github.io/turtledove/)
dictionary AuctionReportBuyerDebugModeConfig {
  boolean enabled = false;

  // Must only be provided if `enabled` is true.
  bigint? debugKey;
};