// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary AudioDecoderConfig {
  required DOMString codec;
  required unsigned long sampleRate;
  required unsigned long numberOfChannels;
  BufferSource description;
};