// Source: Web Audio API 1.1 (https://www.w3.org/TR/webaudio-1.1/)
dictionary AudioProcessingEventInit : EventInit {
    required double playbackTime;
    required AudioBuffer inputBuffer;
    required AudioBuffer outputBuffer;
};