// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary AudioDecoderConfig {
  required DOMString codec;
  required [EnforceRange] unsigned long sampleRate;
  required [EnforceRange] unsigned long numberOfChannels;
  AllowSharedBufferSource description;
};