// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary AudioDataInit {
  required AudioSampleFormat sampleFormat;
  required float sampleRate;
  required unsigned long numberOfFrames;
  required unsigned long numberOfChannels;
  required long long timestamp;    // microseconds
  required BufferSource data;
};