// Source: WebCodecs (https://wicg.github.io/web-codecs/)
[Exposed=(Window,DedicatedWorker)]
interface AudioFrame {
  constructor(AudioFrameInit init);
  readonly attribute DOMHighResTimeStamp timestamp;
  readonly attribute AudioBuffer? buffer;
  undefined close();
};