// Source: Web Audio API 1.1 (https://www.w3.org/TR/webaudio-1.1/)
dictionary AudioRenderCapacityEventInit : EventInit {
    double timestamp = 0;
    double averageLoad = 0;
    double peakLoad = 0;
    double underrunRatio = 0;
};