// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary AudioEncoderConfig {
  required DOMString codec;
  unsigned long sampleRate;
  unsigned long numberOfChannels;
  unsigned long long bitrate;
};