// Source: Web Authentication: An API for accessing Public Key Credentials - Level 3 (https://www.w3.org/TR/webauthn-3/)
dictionary AuthenticationExtensionsClientInputsJSON {
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 3 (https://www.w3.org/TR/webauthn-3/)
partial dictionary AuthenticationExtensionsClientInputsJSON {
  DOMString appid;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 3 (https://www.w3.org/TR/webauthn-3/)
partial dictionary AuthenticationExtensionsClientInputsJSON {
  DOMString appidExclude;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 3 (https://www.w3.org/TR/webauthn-3/)
partial dictionary AuthenticationExtensionsClientInputsJSON {
    boolean credProps;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 3 (https://www.w3.org/TR/webauthn-3/)
partial dictionary AuthenticationExtensionsClientInputsJSON {
    AuthenticationExtensionsPRFInputsJSON prf;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 3 (https://www.w3.org/TR/webauthn-3/)
partial dictionary AuthenticationExtensionsClientInputsJSON {
    AuthenticationExtensionsLargeBlobInputsJSON largeBlob;
};