// Source: Protected Audience (formerly FLEDGE) (https://wicg.github.io/turtledove/)
dictionary BiddingBrowserSignals {
  required DOMString topWindowHostname;
  required USVString seller;
  required long joinCount;
  required long bidCount;
  required long recency;
  required long adComponentsLimit;
  required unsigned short multiBidLimit;

  USVString topLevelSeller;
  sequence<PreviousWin> prevWinsMs;
  object wasmHelper;
  unsigned long dataVersion;
  boolean forDebuggingOnlyInCooldownOrLockout = false;
};