// Source: Web Bluetooth Scanning (https://bluetooth.spec.whatwg.org/scanning.html)
[Exposed=Window, SecureContext]
interface BluetoothManufacturerDataFilter {
  constructor(optional object init);
  readonly maplike<unsigned short, BluetoothDataFilter>;
};