// Source: Web Bluetooth (https://bluetooth.spec.whatwg.org/)
[SecureContext]
interface mixin BluetoothDeviceEventHandlers {
  attribute EventHandler onadvertisementreceived;
  attribute EventHandler ongattserverdisconnected;
};