// Source: CSSOM View Module Level 1 (https://www.w3.org/TR/cssom-view-1/)
dictionary BoxQuadOptions {
  CSSBoxType box = "border";
  GeometryNode relativeTo; // XXX default document (i.e. viewport)
};