// Source: Region Capture (https://w3c.github.io/mediacapture-region/)
[Exposed = Window]
interface BrowserCaptureMediaStreamTrack : MediaStreamTrackOrSubclassThereof {
  Promise<undefined> cropTo(CropTarget? cropTarget);
  BrowserCaptureMediaStreamTrack clone();
};