// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=(Window,Worker,PaintWorklet)]
interface CanvasFilter {
  constructor(optional (CanvasFilterInput or sequence<CanvasFilterInput>) filters);
};