// Source: Capture Handle - Bootstrapping Collaboration when Screensharing (https://w3c.github.io/mediacapture-handle/identity/)
dictionary CaptureHandleChangeEventInit : EventInit {
  CaptureHandle captureHandle;
};