// Source: Screen Capture (https://www.w3.org/TR/screen-capture/)
[Exposed=Window, SecureContext]
interface CaptureController : EventTarget {
  constructor();
  undefined setFocusBehavior(CaptureStartFocusBehavior focusBehavior);
};

// Source: Captured Mouse Events (https://screen-share.github.io/captured-mouse-events/)
partial interface CaptureController {
  attribute EventHandler oncapturedmousechange;
};

// Source: Captured Surface Control (https://w3c.github.io/mediacapture-surface-control/)
partial interface CaptureController {
  sequence<long> getSupportedZoomLevels();
  readonly attribute long? zoomLevel;
  Promise<undefined> increaseZoomLevel();
  Promise<undefined> decreaseZoomLevel();
  Promise<undefined> resetZoomLevel();
  attribute EventHandler onzoomlevelchange;
};

// Source: Captured Surface Control (https://w3c.github.io/mediacapture-surface-control/)
partial interface CaptureController {
  constructor();
  Promise<undefined> forwardWheel(HTMLElement? element);
};