// Source: DOM Standard (https://dom.spec.whatwg.org/)
interface mixin ChildNode {
  [CEReactions, Unscopable] undefined before((Node or TrustedScript or DOMString)... nodes);
  [CEReactions, Unscopable] undefined after((Node or TrustedScript or DOMString)... nodes);
  [CEReactions, Unscopable] undefined replaceWith((Node or TrustedScript or DOMString)... nodes);
  [CEReactions, Unscopable] undefined remove();
};