// Source: Compute and System Pressure Level 1 (https://wicg.github.io/compute-pressure/)
dictionary ComputePressureRecord {
  ComputePressureSource source;
  ComputePressureState state;
  sequence<ComputePressureFactor> factors;
  DOMHighResTimeStamp time;
};