// Source: Compute Pressure API (https://wicg.github.io/compute-pressure/)
callback ComputePressureUpdateCallback = undefined (
  sequence<ComputePressureEntry> entries,
  ComputePressureObserver observer
);