// Source: Media Capture and Streams (https://www.w3.org/TR/mediacapture-streams/)
dictionary ConstrainBooleanOrDOMStringParameters {
  (boolean or DOMString) exact;
  (boolean or DOMString) ideal;
};