// Source: Content Index (https://wicg.github.io/content-index/spec/)
[Exposed=(Window,Worker)]
interface ContentIndex {
  Promise<void> add(ContentDescription description);
  Promise<void> delete(DOMString id);
  Promise<sequence<ContentDescription>> getAll();
};