// Source: Content Index (https://wicg.github.io/content-index/spec/)
[Constructor(DOMString type, ContentIndexEventInit init), Exposed=ServiceWorker]
interface ContentIndexEvent : ExtendableEvent {
  readonly attribute DOMString id;
};