// Source: Cookie Store API Standard (https://cookiestore.spec.whatwg.org/)
dictionary CookieInit {
  required USVString name;
  required USVString value;
  DOMHighResTimeStamp? expires = null;
  USVString? domain = null;
  USVString path = "/";
  CookieSameSite sameSite = "strict";
  boolean partitioned = false;
  long long? maxAge = null;
};