// Source: Crash Reporting (https://wicg.github.io/crash-reporting/)
dictionary CrashReportBody : ReportBody {
  DOMString reason;
  DOMString stack;
  boolean is_top_level;
  DocumentVisibilityState visibility_state;
};