// Source: Writing Assistance APIs (https://webmachinelearning.github.io/writing-assistance-apis/)
[Exposed=Window, SecureContext]
interface CreateMonitor : EventTarget {
  attribute EventHandler ondownloadprogress;
};