// Source: Web Publications (https://www.w3.org/TR/wpub/)
dictionary CreatorInfo {
             sequence<DOMString>         type;
    required sequence<LocalizableString> name;
             DOMString                   id;
             DOMString                   url;
};