// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
dictionary CredentialRequestOptions {
  CredentialMediationRequirement mediation = "optional";
  AbortSignal signal;
};

// Source: Digital Credentials (https://w3c-fedid.github.io/digital-credentials/)
partial dictionary CredentialRequestOptions {
  DigitalCredentialRequestOptions digital;
};

// Source: WebOTP API (https://wicg.github.io/web-otp/)
partial dictionary CredentialRequestOptions {
    OTPCredentialRequestOptions otp;
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
partial dictionary CredentialRequestOptions {
  boolean password = false;
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
partial dictionary CredentialRequestOptions {
  FederatedCredentialRequestOptions federated;
};

// Source: Federated Credential Management API (https://www.w3.org/TR/fedcm-1/)
partial dictionary CredentialRequestOptions {
  IdentityCredentialRequestOptions identity;
};

// Source: Web Authentication: An API for accessing Public Key Credentials - Level 3 (https://www.w3.org/TR/webauthn-3/)
partial dictionary CredentialRequestOptions {
    PublicKeyCredentialRequestOptions      publicKey;
};