// Source: Web Authentication: An API for accessing Public Key Credentials - Level 3 (https://www.w3.org/TR/webauthn-3/)
dictionary CredentialPropertiesOutput {
    boolean rk;
    DOMString authenticatorDisplayName;
};