// Source: CSS Typed OM Level 1 (https://www.w3.org/TR/css-typed-om-1/)
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSColorValue : CSSStyleValue {
    CSSRGB toRGB();
    CSSHSL toHSL();
    CSSHWB toHWB();
    CSSGray toGray();
    CSSLCH toLCH();
    CSSLab toLab();
    CSSColor toColor(CSSKeywordish colorspace);
    CSSDeviceCMYK toDeviceCMYK();

    [Exposed=Window] static CSSColorValue parse(USVString cssText);
};