// Source: Media Queries Level 5 (https://www.w3.org/TR/mediaqueries-5/)
[Exposed=Window]
interface CSSCustomMediaRule : CSSRule {
    readonly attribute CSSOMString name;
    readonly attribute CustomMediaQuery query;
};