// Source: CSS Typed OM Level 1 (https://www.w3.org/TR/css-typed-om-1/)
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSColor : CSSColorValue {
    constructor(CSSKeywordish colorspace, sequence<CSSNumberish> channels, optional CSSNumberish alpha = 1);
    attribute CSSKeywordish colorspace;
    attribute CSSPercentishArray channels;
    attribute CSSNumberish alpha;
};