// Source: CSS Fonts Module Level 4 (https://www.w3.org/TR/css-fonts-4/)
[Exposed=Window]
interface CSSFontFaceRule : CSSRule {
  [SameObject, PutForwards=cssText] readonly attribute CSSFontFaceDescriptors style;
};