// Source: CSS Fonts Module Level 5 (https://www.w3.org/TR/css-fonts-5/)
[Exposed=Window]
interface CSSFontFaceRule : CSSRule {
  [SameObject, PutForwards=cssText] readonly attribute CSSFontFaceDescriptors style;
};