// Source: CSS Nesting Module (https://www.w3.org/TR/css-nesting-1/)
[Exposed=Window]
interface CSSNestRule : CSSGroupingRule {
  [SameObject, PutForwards=cssText] readonly attribute CSSStyleProperties style;
};