// Source: CSS Anchor Positioning (https://www.w3.org/TR/css-anchor-position-1/)
[Exposed=Window]
interface CSSPositionTryRule : CSSRule {
  readonly attribute CSSOMString name;
  [SameObject, PutForwards=cssText] readonly attribute CSSPositionTryDescriptors style;
};