// Source: CSS Object Model (CSSOM) (https://www.w3.org/TR/cssom-1/)
[Exposed=Window]
interface CSSStyleRule : CSSGroupingRule {
  attribute CSSOMString selectorText;
  [SameObject, PutForwards=cssText] readonly attribute CSSStyleProperties style;
};

// Source: CSS Typed OM Level 1 (https://www.w3.org/TR/css-typed-om-1/)
partial interface CSSStyleRule {
    [SameObject] readonly attribute StylePropertyMap styleMap;
};