// Source: CSS View Transitions Module Level 2 (https://drafts.csswg.org/css-view-transitions-2/)
[Exposed=Window]
interface CSSViewTransitionRule : CSSRule {
  readonly attribute CSSOMString navigationConditionText;
  attribute ViewTransitionTrigger trigger;
};