// Source: File and Directory Entries API (https://wicg.github.io/entries-api/)
partial interface DataTransferItem {
    FileSystemEntry? webkitGetAsEntry();
};

// Source: File System Access (https://wicg.github.io/file-system-access/)
partial interface DataTransferItem {
    Promise<FileSystemHandle?> getAsFileSystemHandle();
};