// Source: WebTransport (https://w3c.github.io/webtransport/)
[Exposed=(Window,Worker)]
interface DatagramDuplexStream {
  readonly attribute ReadableStream readable;
  readonly attribute WritableStream writable;
};