// Source: Compression Standard (https://compression.spec.whatwg.org/)
[Exposed=*]
interface DecompressionStream {
  constructor(CompressionFormat format);
};

// Source: Compression Standard (https://compression.spec.whatwg.org/)
DecompressionStream includes GenericTransformStream;