// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Global=(Worker,DedicatedWorker),Exposed=DedicatedWorker]
interface DedicatedWorkerGlobalScope : WorkerGlobalScope {
  [Replaceable] readonly attribute DOMString name;

  undefined postMessage(any message, sequence<object> transfer);
  undefined postMessage(any message, optional PostMessageOptions options = {});

  undefined close();

  attribute EventHandler onmessage;
  attribute EventHandler onmessageerror;
};

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
DedicatedWorkerGlobalScope includes AnimationFrameProvider;