// Source: Deprecation Reporting (https://wicg.github.io/deprecation-reporting/)
dictionary DeprecationReportBody : ReportBody {
  DOMString id;
  object? anticipatedRemoval;
  DOMString message;
  DOMString? sourceFile;
  unsigned long? lineNumber;
  unsigned long? columnNumber;
};