// Source: Digital Credentials (https://wicg.github.io/digital-credentials/)
[Exposed=Window, SecureContext]
interface DigitalCredential : Credential {
  readonly attribute DOMString protocol;
  [SameObject] readonly attribute object data;
};