// Source: Font Metrics API Level 1 (https://drafts.css-houdini.org/font-metrics-api-1/)
partial interface Document {
    FontMetrics measureElement(Element element);
    FontMetrics measureText(DOMString text, StylePropertyMapReadOnly styleMap);
};

// Source: Fullscreen API Standard (https://fullscreen.spec.whatwg.org/)
partial interface Document {
  [LegacyLenientSetter] readonly attribute boolean fullscreenEnabled;
  [LegacyLenientSetter, Unscopable] readonly attribute boolean fullscreen; // historical

  Promise<undefined> exitFullscreen();

  attribute EventHandler onfullscreenchange;
  attribute EventHandler onfullscreenerror;
};

// Source: The Storage Access API (https://privacycg.github.io/storage-access/)
partial interface Document {
  Promise<boolean> hasStorageAccess();
  Promise<undefined> requestStorageAccess();
};

// Source: Federated Learning of Cohorts (https://wicg.github.io/floc/)
partial interface Document {
    Promise<InterestCohort> interestCohort();
};

// Source: Page Lifecycle (https://wicg.github.io/page-lifecycle/)
partial interface Document {
    attribute EventHandler onfreeze;
    attribute EventHandler onresume;
    readonly attribute boolean wasDiscarded;
};

// Source: Text Fragments (https://wicg.github.io/scroll-to-text-fragment/)
partial interface Document {
    [SameObject] readonly attribute FragmentDirective fragmentDirective;
};

// Source: CSS Font Loading Module Level 3 (https://www.w3.org/TR/css-font-loading-3/)
Document includes FontFaceSource;

// Source: CSS Regions Module Level 1 (https://www.w3.org/TR/css-regions-1/)
partial interface Document {
  readonly attribute NamedFlowMap namedFlows;
};

// Source: CSSOM View Module (https://www.w3.org/TR/cssom-view-1/)
partial interface Document {
  Element? elementFromPoint(double x, double y);
  sequence<Element> elementsFromPoint(double x, double y);
  CaretPosition? caretPositionFromPoint(double x, double y);
  readonly attribute Element? scrollingElement;
};

// Source: CSSOM View Module (https://www.w3.org/TR/cssom-view-1/)
Document includes GeometryUtils;

// Source: Permissions Policy (https://www.w3.org/TR/permissions-policy-1/)
partial interface Document {
    [SameObject] readonly attribute PermissionsPolicy permissionsPolicy;
};

// Source: Picture-in-Picture (https://www.w3.org/TR/picture-in-picture/)
partial interface Document {
  readonly attribute boolean pictureInPictureEnabled;

  [NewObject] Promise<undefined> exitPictureInPicture();
};

// Source: Pointer Lock 2.0 (https://www.w3.org/TR/pointerlock-2/)
partial interface Document {
  attribute EventHandler onpointerlockchange;
  attribute EventHandler onpointerlockerror;
  undefined exitPointerLock();
};

// Source: Selection API (https://www.w3.org/TR/selection-api/)
partial interface Document {
  Selection? getSelection();
};

// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
partial interface Document {
  readonly attribute SVGSVGElement? rootElement;
};

// Source: Web Animations (https://www.w3.org/TR/web-animations-1/)
partial interface Document {
    readonly attribute DocumentTimeline timeline;
};