// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
interface mixin DocumentAndElementEventHandlers {
  attribute EventHandler oncopy;
  attribute EventHandler oncut;
  attribute EventHandler onpaste;
};