// Source: Document Picture-in-Picture Specification (https://wicg.github.io/document-picture-in-picture/)
dictionary DocumentPictureInPictureOptions {
  [EnforceRange] unsigned long long width = 0;
  [EnforceRange] unsigned long long height = 0;
  boolean disallowReturnToOpener = false;
};