// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface DOMParser {
  constructor();

  [NewObject] Document parseFromString(HTMLString string, DOMParserSupportedType type);
};