// Source: WebCodecs (https://wicg.github.io/web-codecs/)
[Exposed=(Window,DedicatedWorker)]
interface EncodedVideoChunk {
  constructor(EncodedVideoChunkInit init);
  readonly attribute EncodedVideoChunkType type;
  readonly attribute DOMHighResTimeStamp timestamp;
  readonly attribute DOMHighResTimeStamp? duration;
  readonly attribute ArrayBuffer data;
};