// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
[Exposed=(Window,DedicatedWorker)]
interface EncodedVideoChunk {
  constructor(EncodedVideoChunkInit init);
  readonly attribute EncodedVideoChunkType type;
  readonly attribute long long timestamp;    // microseconds
  readonly attribute long long? duration;    // microseconds
  readonly attribute unsigned long byteLength;

  undefined copyTo(ArrayBufferView dst);
};