// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary EncodedVideoChunkInit {
  required EncodedVideoChunkType type;
  required unsigned long long timestamp;
  unsigned long long duration;
  required BufferSource data;
};