// Source: WebCodecs (https://w3c.github.io/webcodecs/)
dictionary EncodedAudioChunkInit {
  required EncodedAudioChunkType type;
  required unsigned long long timestamp;
  required BufferSource data;
};