// Source: WebCodecs (https://wicg.github.io/web-codecs/)
dictionary EncodedVideoChunkInit {
  required EncodedVideoChunkType type;
  required unsigned long long timestamp;
  unsigned long long duration;
  required BufferSource data;
};