// Source: WebCodecs (https://wicg.github.io/web-codecs/)
dictionary EncodedVideoChunkInit {
  required EncodedVideoChunkType type;
  required DOMHighResTimeStamp timestamp;
  DOMHighResTimeStamp duration;
  required BufferSource data;
};