// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary EncodedAudioChunkInit {
  required EncodedAudioChunkType type;
  required unsigned long long timestamp;
  required BufferSource data;
};