// Source: WebGL EXT_shader_texture_lod Khronos Ratified Extension Specification (https://www.khronos.org/registry/webgl/extensions/EXT_shader_texture_lod/)
[LegacyNoInterfaceObject]
interface EXT_shader_texture_lod {
};