// Source: WebGL EXT_color_buffer_float Extension Specification (https://www.khronos.org/registry/webgl/extensions/EXT_color_buffer_float/)
[LegacyNoInterfaceObject]
interface EXT_color_buffer_float {
};