// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
[Exposed=Window,
 SecureContext]
interface FederatedCredential : Credential {
  constructor(FederatedCredentialInit data);
  readonly attribute USVString provider;
  readonly attribute DOMString? protocol;
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface FederatedCredential {
  Promise<FederatedTokens> login(optional FederatedAccountLoginRequest request = {});
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface FederatedCredential {
  Promise<undefined> revoke(USVString hint);
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface FederatedCredential {
  Promise<undefined> logout();
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface FederatedCredential {
  static Promise<undefined> logoutRPs(sequence<FederatedCredentialLogoutRpsRequest> logoutRequests);
};

// Source: Credential Management Level 1 (https://www.w3.org/TR/credential-management-1/)
FederatedCredential includes CredentialUserData;