// Source: Fenced frame (https://wicg.github.io/fenced-frame/)
[Exposed=Window]
interface FencedFrameConfig {
  constructor(USVString url);
  readonly attribute FencedFrameConfigURL? url;
  readonly attribute FencedFrameConfigSize? width;
  readonly attribute FencedFrameConfigSize? height;
};