// Source: Fenced Frame (https://wicg.github.io/fenced-frame/)
dictionary FenceEvent {
  required DOMString eventType;
  required DOMString eventData;
  required sequence<FenceReportingDestination> destination;
  boolean once = false;
};