// Source: Fenced Frame (https://wicg.github.io/fenced-frame/)
[Exposed=Window, Serializable]
interface FencedFrameConfig {
  constructor(USVString url);

  readonly attribute FencedFrameConfigSize? containerWidth;
  readonly attribute FencedFrameConfigSize? containerHeight;
  readonly attribute FencedFrameConfigSize? contentWidth;
  readonly attribute FencedFrameConfigSize? contentHeight;

  undefined setSharedStorageContext(DOMString contextString);
};