// Source: Fenced Frame (https://wicg.github.io/fenced-frame/)
[Exposed=Window]
interface Fence {
    undefined reportEvent(ReportEventType event);
    undefined setReportEventDataForAutomaticBeacons(FenceEvent event);
    sequence<FencedFrameConfig> getNestedConfigs();
};