// Source: Fenced Frame (https://wicg.github.io/fenced-frame/)
[Exposed=Window]
interface Fence {
    undefined reportEvent(optional ReportEventType event = {});
    undefined setReportEventDataForAutomaticBeacons(optional FenceEvent event = {});
    sequence<FencedFrameConfig> getNestedConfigs();
    undefined notifyEvent(Event event);
};