// Source: Fenced Frame (https://wicg.github.io/fenced-frame/)
[Exposed=Window, Serializable]
interface FencedFrameConfig {
  constructor(USVString url);
  undefined setSharedStorageContext(DOMString contextString);
};