// Source: CSS Font Loading Module Level 3 (https://www.w3.org/TR/css-font-loading-3/)
interface FontFacePalette {
  iterable<DOMString>;
  readonly attribute unsigned long length;
  getter DOMString (unsigned long index);
  readonly attribute bool usableWithLightBackground;
  readonly attribute bool usableWithDarkBackground;
};