// Source: Local Font Access API (https://wicg.github.io/local-font-access/)
[Exposed=Window]
interface FontMetadata {
  Promise<Blob> blob();

  // Names
  readonly attribute USVString postscriptName;
  readonly attribute USVString fullName;
  readonly attribute USVString family;
  readonly attribute USVString style;

  // Metrics
  readonly attribute boolean italic;
  readonly attribute float stretch;
  readonly attribute float weight;
};