// Source: Fullscreen API Standard (https://fullscreen.spec.whatwg.org/)
dictionary FullscreenOptions {
  FullscreenNavigationUI navigationUI = "auto";
};

// Source: Window Management (https://www.w3.org/TR/window-management/)
partial dictionary FullscreenOptions {
  ScreenDetailed screen;
};