// Source: CSS Functions and Mixins Module (https://www.w3.org/TR/css-mixins-1/)
dictionary FunctionParameter {
  required CSSOMString name;
  required CSSOMString type;
  CSSOMString? defaultValue;
};