// Source: CSS Functions and Mixins Module (https://drafts.csswg.org/css-mixins-1/)
dictionary FunctionParameter {
  required CSSOMString name;
  required CSSOMString type;
  CSSOMString? defaultValue;
};