// Source: Web Audio API 1.1 (https://www.w3.org/TR/webaudio-1.1/)
[Exposed=Window]
interface GainNode : AudioNode {
    constructor (BaseAudioContext context, optional GainOptions options = {});
    readonly attribute AudioParam gain;
};