// Source: Gamepad (https://www.w3.org/TR/gamepad/)
[Exposed=Window]

interface GamepadEvent: Event {
  constructor(DOMString type, optional GamepadEventInit eventInitDict = {});
  [SameObject] readonly attribute Gamepad gamepad;
};