// Source: Gamepad (https://www.w3.org/TR/gamepad/)
[Exposed=Window]
interface GamepadHapticActuator {
  [SameObject] readonly attribute FrozenArray<GamepadHapticEffectType> effects;
  Promise<GamepadHapticsResult> playEffect(
      GamepadHapticEffectType type,
      optional GamepadEffectParameters params = {}
  );
  Promise<GamepadHapticsResult> reset();
};

// Source: Gamepad Extensions (https://w3c.github.io/gamepad/extensions.html)
[Exposed=Window]
partial interface GamepadHapticActuator {
  Promise<boolean> pulse(double value, double duration);
};