// Source: Gamepad Extensions (https://w3c.github.io/gamepad/extensions.html)
partial interface Gamepad {
  readonly attribute GamepadHand hand;
  readonly attribute FrozenArray<GamepadHapticActuator> hapticActuators;
  readonly attribute GamepadPose? pose;
  readonly attribute FrozenArray<GamepadTouch>? touchEvents;
};