// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=Window]
interface GPUAdapter {
    readonly attribute DOMString name;
    [SameObject] readonly attribute GPUSupportedFeatures features;
    [SameObject] readonly attribute GPUSupportedLimits limits;

    Promise<GPUDevice> requestDevice(optional GPUDeviceDescriptor descriptor = {});
};