// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, Worker), SecureContext]
interface GPUBindGroup {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUBindGroup includes GPUObjectBase;