// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
enum GPUBlendFactor {
    "zero",
    "one",
    "src-component",
    "one-minus-src-component",
    "src-alpha",
    "one-minus-src-alpha",
    "dst-component",
    "one-minus-dst-component",
    "dst-alpha",
    "one-minus-dst-alpha",
    "src-alpha-saturated",
    "blendcolor-component",
    "one-minus-blendcolor-component"
};