// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, Worker), SecureContext]
interface GPUBindGroupLayout {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUBindGroupLayout includes GPUObjectBase;