// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
enum GPUCompareFunction {
    "never",
    "less",
    "equal",
    "less-equal",
    "greater",
    "not-equal",
    "greater-equal",
    "always"
};