// Source: WebGPU (https://www.w3.org/TR/webgpu/)
dictionary GPUCopyExternalImageSourceInfo {
    required GPUCopyExternalImageSource source;
    GPUOrigin2D origin = {};
    boolean flipY = false;
};