// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=Window]
interface GPUCanvasContext {
    GPUSwapChain configureSwapChain(GPUSwapChainDescriptor descriptor);

    GPUTextureFormat getSwapChainPreferredFormat(GPUAdapter adapter);
};