// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker)]
interface GPUCommandBuffer {
    readonly attribute Promise<double> executionTime;
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUCommandBuffer includes GPUObjectBase;