// Source: WebGPU (https://www.w3.org/TR/webgpu/)
// May represent WGSL's bool, f32, i32, u32, and f16 if enabled.

[Exposed=(Window, DedicatedWorker, ServiceWorker), SecureContext]
interface GPUComputePipeline {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePipeline includes GPUObjectBase;

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUComputePipeline includes GPUPipelineBase;