// Source: WebGPU (https://www.w3.org/TR/webgpu/)
dictionary GPUImageCopyExternalImage {
    required GPUImageCopyExternalImageSource source;
    GPUOrigin2D origin = {};
    boolean flipY = false;
};