// Source: WebGPU (https://www.w3.org/TR/webgpu/)
typedef (ImageBitmap or
         HTMLVideoElement or
         VideoFrame or
         HTMLCanvasElement or
         OffscreenCanvas) GPUImageCopyExternalImageSource;