// Source: WebGPU (https://www.w3.org/TR/webgpu/)
dictionary GPUPipelineLayoutDescriptor
         : GPUObjectDescriptorBase {
    required sequence<GPUBindGroupLayout?> bindGroupLayouts;
    GPUSize32 immediateSize = 0;
};