// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker, ServiceWorker), SecureContext]
interface GPUQuerySet {
    undefined destroy();

    readonly attribute GPUQueryType type;
    readonly attribute GPUSize32Out count;
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUQuerySet includes GPUObjectBase;