// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker)]
interface GPUQuerySet {
    undefined destroy();
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUQuerySet includes GPUObjectBase;