// Source: WebGPU (https://www.w3.org/TR/webgpu/)
dictionary GPURenderPassDepthStencilAttachment {
    required GPUTextureView view;

    float depthClearValue = 0;
    required GPULoadOp depthLoadOp;
    required GPUStoreOp depthStoreOp;
    boolean depthReadOnly = false;

    GPUStencilValue stencilClearValue = 0;
    required GPULoadOp stencilLoadOp;
    required GPUStoreOp stencilStoreOp;
    boolean stencilReadOnly = false;
};