// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker, ServiceWorker), SecureContext]
interface GPURenderPipeline {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPURenderPipeline includes GPUObjectBase;

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPURenderPipeline includes GPUPipelineBase;