// Source: WebGPU (https://www.w3.org/TR/webgpu/)
dictionary GPURequestAdapterOptions {
    DOMString featureLevel;
    GPUPowerPreference powerPreference;
    boolean forceFallbackAdapter = false;
};