// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
interface GPUSwapChain {
    GPUTexture getCurrentTexture();
};

// Source: WebGPU (https://gpuweb.github.io/gpuweb/)
GPUSwapChain includes GPUObjectBase;