// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker)]
interface GPUTexture {
    GPUTextureView createView(optional GPUTextureViewDescriptor descriptor = {});

    undefined destroy();
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUTexture includes GPUObjectBase;