// Source: WebGPU (https://www.w3.org/TR/webgpu/)
[Exposed=(Window, DedicatedWorker, ServiceWorker), SecureContext]
interface GPUTextureView {
};

// Source: WebGPU (https://www.w3.org/TR/webgpu/)
GPUTextureView includes GPUObjectBase;