// Source: Handwriting Recognition API (https://wicg.github.io/handwriting-recognition/)
dictionary HandwritingDrawingSegment {
  required unsigned long strokeIndex;
  required unsigned long beginPointIndex;
  required unsigned long endPointIndex;
};