// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface HTMLAreaElement : HTMLElement {
  [HTMLConstructor] constructor();

  [CEReactions, Reflect] attribute DOMString alt;
  [CEReactions, Reflect] attribute DOMString coords;
  [CEReactions, Reflect] attribute DOMString shape;
  [CEReactions, Reflect] attribute DOMString target;
  [CEReactions, Reflect] attribute DOMString download;
  [CEReactions, Reflect] attribute USVString ping;
  [CEReactions, Reflect] attribute DOMString rel;
  [SameObject, PutForwards=value, Reflect="rel"] readonly attribute DOMTokenList relList;
  [CEReactions] attribute DOMString referrerPolicy;

  // also has obsolete members
};

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
HTMLAreaElement includes HTMLHyperlinkElementUtils;

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
partial interface HTMLAreaElement {
  [CEReactions, Reflect] attribute boolean noHref;
};

// Source: Attribution Reporting (https://wicg.github.io/attribution-reporting-api/)
HTMLAreaElement includes HTMLAttributionSrcElementUtils;