// Source: Media Capture and Streams Extensions (https://w3c.github.io/mediacapture-extensions/)
dictionary HTMLMediaStreamConstraints {
  MediaTrackConstraintSet video;
  MediaTrackConstraintSet audio;
};