// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface HTMLScriptElement : HTMLElement {
  [HTMLConstructor] constructor();

  [CEReactions, Reflect] attribute DOMString type;
  [CEReactions] attribute (TrustedScriptURL or USVString) src;
  [CEReactions, Reflect] attribute boolean noModule;
  [CEReactions] attribute boolean async;
  [CEReactions, Reflect] attribute boolean defer;
  [SameObject, PutForwards=value, Reflect] readonly attribute DOMTokenList blocking;
  [CEReactions] attribute DOMString? crossOrigin;
  [CEReactions] attribute DOMString referrerPolicy;
  [CEReactions, Reflect] attribute DOMString integrity;
  [CEReactions] attribute DOMString fetchPriority;

  // innerText and textContent shadow HTMLElement's and Node's, to add Trusted Types checks
  [CEReactions] attribute (TrustedScript or [LegacyNullToEmptyString] DOMString) innerText;
  [CEReactions] attribute (TrustedScript or DOMString)? textContent;
  [CEReactions] attribute (TrustedScript or DOMString) text;

  static boolean supports(DOMString type);

  // also has obsolete members
};

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
partial interface HTMLScriptElement {
  [CEReactions, Reflect] attribute DOMString charset;
  [CEReactions, Reflect] attribute DOMString event;
  [CEReactions, Reflect="for"] attribute DOMString htmlFor;
};