// Source: Priority Hints (https://wicg.github.io/priority-hints/)
partial interface HTMLIFrameElement {
    [CEReactions] attribute DOMString importance;
};

// Source: Content Security Policy: Embedded Enforcement (https://www.w3.org/TR/csp-embedded-enforcement/)
partial interface HTMLIFrameElement {
  [CEReactions] attribute DOMString csp;
};

// Source: Permissions Policy (https://www.w3.org/TR/permissions-policy-1/)
partial interface HTMLIFrameElement {
    [SameObject] readonly attribute PermissionsPolicy permissionsPolicy;
};