// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface HTMLStyleElement : HTMLElement {
  [HTMLConstructor] constructor();

  attribute boolean disabled;
  [CEReactions, Reflect] attribute DOMString media;
  [SameObject, PutForwards=value, Reflect] readonly attribute DOMTokenList blocking;

  // also has obsolete members
};

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
HTMLStyleElement includes LinkStyle;

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
partial interface HTMLStyleElement {
  [CEReactions, Reflect] attribute DOMString type;
};