// Source: The <model> element (https://immersive-web.github.io/model-element/)
[Exposed=Window]
interface HTMLModelElement : HTMLElement {

  readonly attribute Promise<HTMLModelElement> ready;
  readonly attribute DOMPointReadOnly boundingBoxCenter;
  readonly attribute DOMPointReadOnly boundingBoxExtents;
  attribute DOMMatrixReadOnly entityTransform;

};