// Source: Media Capture and Streams Extensions (https://w3c.github.io/mediacapture-extensions/)
enum HumanFaceDetectionModeEnum {
  "none",
  "bounding-box",
  "bounding-box-with-landmark-center-point",
};