// Source: Federated Credential Management API (https://www.w3.org/TR/fedcm-1/)
dictionary IdentityProviderClientMetadata {
  USVString privacy_policy_url;
  USVString terms_of_service_url;
  boolean client_is_third_party_to_top_frame_origin = false;
};