// Source: Federated Credential Management API (https://www.w3.org/TR/fedcm-1/)
dictionary IdentityProviderAccount {
  required USVString id;
  USVString name;
  USVString email;
  USVString tel;
  USVString username;
  USVString given_name;
  USVString picture;
  sequence<USVString> approved_clients;
  sequence<DOMString> login_hints;
  sequence<DOMString> domain_hints;
  sequence<DOMString> label_hints;
};