// Source: Federated Credential Management API (https://www.w3.org/TR/fedcm-1/)
[Exposed=Window, SecureContext] interface IdentityProvider {
    static undefined close();
    static Promise<sequence<IdentityUserInfo>> getUserInfo(IdentityProviderConfig config);
};