// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
dictionary IdentityProviderRequestOptions : IdentityProviderConfig {
  USVString nonce;
  DOMString loginHint;
  DOMString domainHint;
};