// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
interface IdentityCredential : Credential {
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface IdentityCredential {
  Promise<FederatedTokens> login(optional FederatedAccountLoginRequest request = {});
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface IdentityCredential {
  Promise<undefined> revoke(USVString hint);
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface IdentityCredential {
  Promise<undefined> logout();
};

// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
[Exposed=Window, SecureContext]
partial interface IdentityCredential {
  static Promise<undefined> logoutRPs(sequence<IdentityCredentialLogoutRpsRequest> logoutRequests);
};