// Source: Federated Credential Management API (https://www.w3.org/TR/fedcm-1/)
[Exposed=Window, SecureContext]
interface IdentityCredential : Credential {
  static Promise<undefined> disconnect(IdentityCredentialDisconnectOptions options);
  readonly attribute USVString? token;
  readonly attribute boolean isAutoSelected;
  readonly attribute USVString configURL;
};