// Source: Federated Credential Management API (https://fedidcg.github.io/FedCM/)
dictionary IdentityCredentialRequestOptions {
  required sequence<IdentityProviderConfig> providers;
  IdentityCredentialRequestOptionsContext context = "signin";
};