// Source: WebTransport (https://w3c.github.io/webtransport/)
[ Exposed=(Window,Worker) ]
interface mixin IncomingStream {
  /* a ReadableStream of Uint8Array */
  readonly attribute ReadableStream readable;
  readonly attribute Promise<StreamAbortInfo> readingAborted;
  undefined abortReading(optional StreamAbortInfo abortInfo = {});
};