// Source: Ink API (https://wicg.github.io/ink-enhancement/)
[Exposed=Window]
interface Ink {
    Promise<DelegatedInkTrailPresenter> requestPresenter(
        optional InkPresenterParam param = {});
};