// Source: FLEDGE (https://wicg.github.io/turtledove/)
[Exposed=InterestGroupReportingScriptRunnerGlobalScope,
Global=InterestGroupReportingScriptRunnerGlobalScope]
interface InterestGroupReportingScriptRunnerGlobalScope {
  undefined sendReportTo(DOMString url);
};