// Source: Intervention Reporting (https://wicg.github.io/intervention-reporting/)
dictionary InterventionReportBody : ReportBody {
  DOMString id;
  DOMString message;
  DOMString? sourceFile;
  unsigned long? lineNumber;
  unsigned long? columnNumber;
};