// Source: FLEDGE (https://wicg.github.io/turtledove/)
[Exposed=InterestGroupScoringScriptRunnerGlobalScope,
Global=InterestGroupScoringScriptRunnerGlobalScope]
interface InterestGroupScoringScriptRunnerGlobalScope {
};