// Source: FLEDGE (https://wicg.github.io/turtledove/)
[Exposed=InterestGroupBiddingScriptRunnerGlobalScope,
Global=InterestGroupBiddingScriptRunnerGlobalScope]
interface InterestGroupBiddingScriptRunnerGlobalScope {
  boolean setBid();
  boolean setBid(GenerateBidOutput generateBidOutput);
  undefined setPriority(double priority);
  undefined setPrioritySignalsOverride(DOMString key, double priority);
};