// Source: Subresource Integrity (https://www.w3.org/TR/sri-2/)
dictionary IntegrityViolationReportBody : ReportBody {
  USVString documentURL;
  USVString blockedURL;
  USVString destination;
  boolean   reportOnly;
};