// Source: CSSOM View Module (https://www.w3.org/TR/cssom-view-1/)
dictionary IsVisibleOptions {
    boolean checkInert = false;
    boolean checkOpacity = false;
    boolean checkVisibilityCSS = false;
};