// Source: CSSOM View Module (https://www.w3.org/TR/cssom-view-1/)
dictionary IsVisibleOptions {
    bool checkAriaHidden = false;
    bool checkInert = false;
    bool checkOpacity = false;
    bool checkVisibilityCSS = false;
};