// Source: Keyboard Lock (https://wicg.github.io/keyboard-lock/)
[SecureContext, Exposed=Window] interface Keyboard {
  Promise<undefined> lock(optional sequence<DOMString> keyCodes = []);
  undefined unlock();
};