// Source: Keyboard Lock (https://wicg.github.io/keyboard-lock/)
[SecureContext, Exposed=Window] interface Keyboard {
  Promise<void> lock(optional sequence<DOMString> keyCodes = []);
  void unlock();
};