// Source: Prompt API (https://webmachinelearning.github.io/prompt-api/)
dictionary LanguageModelPromptOptions {
  object responseConstraint;
  boolean omitResponseConstraintInput = false;
  AbortSignal signal;
};