// Source: Prompt API (https://webmachinelearning.github.io/prompt-api/)
dictionary LanguageModelMessageContent {
  required LanguageModelMessageType type;
  required LanguageModelMessageValue value;
};