// Source: Translator and Language Detector APIs (https://webmachinelearning.github.io/translation-api/)
dictionary LanguageDetectorCreateOptions : LanguageDetectorCreateCoreOptions {
  AbortSignal signal;
  CreateMonitorCallback monitor;
};