// Source: Web Publications (https://www.w3.org/TR/wpub/)
dictionary LinkedResource {
    required DOMString           url;
             DOMString           encodingFormat;
             sequence<LocalizableString>   name;
             LocalizableString   description;
             sequence<DOMString> rel;
             DOMString           integrity;
             double              length;
};