// Source: MathML Core (https://mathml-refresh.github.io/mathml-core/)
[Exposed=Window]
interface MathMLElement : Element { };

// Source: MathML Core (https://mathml-refresh.github.io/mathml-core/)
MathMLElement includes GlobalEventHandlers;

// Source: MathML Core (https://mathml-refresh.github.io/mathml-core/)
MathMLElement includes DocumentAndElementEventHandlers;

// Source: MathML Core (https://mathml-refresh.github.io/mathml-core/)
MathMLElement includes HTMLOrForeignElement;

// Source: CSS Object Model (CSSOM) (https://www.w3.org/TR/cssom-1/)
MathMLElement includes ElementCSSInlineStyle;