// Source: MathML Core (https://www.w3.org/TR/mathml-core/)
[Exposed=Window]
interface MathMLElement : Element { };

// Source: MathML Core (https://www.w3.org/TR/mathml-core/)
MathMLElement includes GlobalEventHandlers;

// Source: MathML Core (https://www.w3.org/TR/mathml-core/)
MathMLElement includes DocumentAndElementEventHandlers;

// Source: MathML Core (https://www.w3.org/TR/mathml-core/)
MathMLElement includes HTMLOrForeignElement;