// Source: Media Capture and Streams (https://www.w3.org/TR/mediacapture-streams/)
[Exposed=Window]
interface MediaStreamTrackEvent : Event {
  constructor(DOMString type, MediaStreamTrackEventInit eventInitDict);
  [SameObject] readonly attribute MediaStreamTrack track;
};

// Source: Media Capture and Streams Extensions (https://w3c.github.io/mediacapture-extensions/)
[Exposed=(Window,DedicatedWorker)]
partial interface MediaStreamTrackEvent {
};