// Source: Encrypted Media Extensions (https://www.w3.org/TR/encrypted-media-2/)
enum MediaKeyStatus {
  "usable",
  "expired",
  "released",
  "output-restricted",
  "output-downscaled",
  "usable-in-future",
  "status-pending",
  "internal-error"
};