// Source: MediaStreamTrack Insertable Media Processing using Streams (https://www.w3.org/TR/mediacapture-transform/)
[Exposed=(Window,DedicatedWorker), Transferable]
interface MediaStreamTrackHandle {
   constructor(MediaStreamTrack track);
};