// Source: Media Capture and Streams (https://www.w3.org/TR/mediacapture-streams/)
dictionary MediaStreamConstraints {
  (boolean or MediaTrackConstraints) video = false;
  (boolean or MediaTrackConstraints) audio = false;
};