// Source: MediaStreamTrack Insertable Media Processing using Streams (https://www.w3.org/TR/mediacapture-transform/)
dictionary MediaStreamTrackProcessorInit {
  required MediaStreamTrackOrHandle track;
  [EnforceRange] unsigned short maxBufferSize;
};