// Source: MediaStream Image Capture (https://www.w3.org/TR/image-capture/)
partial dictionary MediaTrackSettings {
  DOMString         whiteBalanceMode;
  DOMString         exposureMode;
  DOMString         focusMode;
  sequence<Point2D> pointsOfInterest;

  double            exposureCompensation;
  double            exposureTime;
  double            colorTemperature;
  double            iso;

  double            brightness;
  double            contrast;
  double            saturation;
  double            sharpness;

  double            focusDistance;
  double            pan;
  double            tilt;
  double            zoom;

  boolean           torch;
};

// Source: Media Capture Depth Stream Extensions (https://www.w3.org/TR/mediacapture-depth/)
partial dictionary MediaTrackSettings {
    // Applies to both depth stream track and color stream track:
    DOMString           videoKind;
};