// Source: Web Neural Network API (https://www.w3.org/TR/webnn/)
dictionary MLArgMinMaxOptions {
  sequence<unsigned long> axes = null;
  boolean keepDimensions = false;
  boolean selectLastIndex = false;
};