// Source: Web Neural Network API (https://www.w3.org/TR/webnn/)
dictionary MLQuantizationSupportLimits {
  MLSupportLimits input;
  MLSupportLimits scale;
  MLSupportLimits zeroPoint;
  MLSupportLimits output;
};