// Source: UI Events (https://www.w3.org/TR/uievents/)
[Exposed=Window]
interface MouseEvent : UIEvent {
  constructor(DOMString type, optional MouseEventInit eventInitDict);
  readonly attribute long screenX;
  readonly attribute long screenY;
  readonly attribute long clientX;
  readonly attribute long clientY;

  readonly attribute boolean ctrlKey;
  readonly attribute boolean shiftKey;
  readonly attribute boolean altKey;
  readonly attribute boolean metaKey;

  readonly attribute short button;
  readonly attribute unsigned short buttons;

  readonly attribute EventTarget? relatedTarget;

  boolean getModifierState(DOMString keyArg);
};

// Source: CSSOM View Module (https://www.w3.org/TR/cssom-view-1/)
partial interface MouseEvent {
  readonly attribute double screenX;
  readonly attribute double screenY;
  readonly attribute double pageX;
  readonly attribute double pageY;
  readonly attribute double clientX;
  readonly attribute double clientY;
  readonly attribute double x;
  readonly attribute double y;
  readonly attribute double offsetX;
  readonly attribute double offsetY;
};

// Source: Pointer Lock 2.0 (https://www.w3.org/TR/pointerlock-2/)
partial interface MouseEvent {
  readonly attribute long movementX;
  readonly attribute long movementY;
};

// Source: UI Events (https://www.w3.org/TR/uievents/)
partial interface MouseEvent {
  // Deprecated in this specification
  undefined initMouseEvent();
};