// Source: CSS Spatial Navigation Module Level 1 (https://www.w3.org/TR/css-nav-1/)
dictionary NavigationEventInit : UIEventInit {
    SpatialNavigationDirection dir;
    EventTarget? relatedTarget = null;
};