// Source: Navigation API (https://wicg.github.io/navigation-api/)
// TODO: rename to NavigationType after https://github.com/w3c/navigation-timing/pull/172 lands.
enum NavigationNavigationType {
  "reload",
  "push",
  "replace",
  "traverse"
};