// Source: Cross-Origin Storage (https://wicg.github.io/cross-origin-storage/)
interface mixin NavigatorCrossOriginStorage {
  [SameObject, SecureContext] readonly attribute CrossOriginStorageManager crossOriginStorage;
};