// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface NavigationPrecommitController {
  undefined redirect(USVString url, optional NavigationNavigateOptions options = {});
  undefined addHandler(NavigationInterceptHandler handler);
};