// Source: Managed Configuration API (https://wicg.github.io/WebApiDevice/managed_config/)
[
  SecureContext,
  Exposed=Window
] interface NavigatorManagedData : EventTarget {
  // Managed Configuration API.
  Promise<record<DOMString, object>> getManagedConfiguration(sequence<DOMString> keys);
  attribute EventHandler onmanagedconfigurationchange;
};

// Source: Device Attributes API (https://wicg.github.io/WebApiDevice/device_attributes/)
partial interface NavigatorManagedData {
  // Device Attributes API.
  Promise<DOMString> getAnnotatedAssetId();
  Promise<DOMString> getAnnotatedLocation();
  Promise<DOMString> getDirectoryId();
  Promise<DOMString> getHostname();
  Promise<DOMString> getSerialNumber();
};