// Source: Navigation API (https://wicg.github.io/app-history/)
dictionary NavigationCurrentEntryChangeEventInit : EventInit {
  NavigationNavigationType? navigationType = null;
  required NavigationHistoryEntry destination;
};