// Source: WebGL OES_fbo_render_mipmap Extension Specification (https://www.khronos.org/registry/webgl/extensions/OES_fbo_render_mipmap/)
[LegacyNoInterfaceObject]
interface OES_fbo_render_mipmap {
};