// Source: Web Audio API 1.1 (https://www.w3.org/TR/webaudio-1.1/)
[Exposed=Window]
interface OfflineAudioCompletionEvent : Event {
    constructor (DOMString type, OfflineAudioCompletionEventInit eventInitDict);
    readonly attribute AudioBuffer renderedBuffer;
};