// Source: Protected Audience (formerly FLEDGE) (https://wicg.github.io/turtledove/)
dictionary PAExtendedHistogramContribution {
  required (PASignalValue or bigint) bucket;
  required (PASignalValue or long) value;
  bigint filteringId = 0;
};