// Source: Private Aggregation API (https://patcg-individual-drafts.github.io/private-aggregation-api/)
dictionary PAHistogramContribution {
  required bigint bucket;
  required long value;
  bigint filteringId = 0;
};