// Source: Web Cryptography API Level 2 (https://www.w3.org/TR/webcrypto-2/)
dictionary Pbkdf2Params : Algorithm {
  required BufferSource salt;
  required [EnforceRange] unsigned long iterations;
  required HashAlgorithmIdentifier hash;
};