// Source: Event Timing API (https://wicg.github.io/event-timing/)
[Exposed=Window]
partial interface Performance {
    [SameObject] readonly attribute EventCounts eventCounts;
};

// Source: Measure Memory API (https://wicg.github.io/performance-measure-memory/)
partial interface Performance {
  [Exposed=(Window,ServiceWorker,SharedWorker), CrossOriginIsolated] Promise<MemoryMeasurement> measureUserAgentSpecificMemory();
};