// Source: Paint Timing (https://www.w3.org/TR/paint-timing/)
[Exposed=Window]
interface PerformancePaintTiming : PerformanceEntry {};

// Source: Paint Timing (https://www.w3.org/TR/paint-timing/)
PerformancePaintTiming includes PaintTimingMixin;