// Source: Navigation Timing Level 2 (https://www.w3.org/TR/navigation-timing-2/)
[Exposed=Window]
interface PerformanceTimingConfidence {
    readonly attribute double randomizedTriggerRate;
    readonly attribute PerformanceTimingConfidenceValue value;
    object toJSON();
};