// Source: Server Timing (https://www.w3.org/TR/server-timing/)
[Exposed=(Window,Worker)]
partial interface PerformanceResourceTiming {
  readonly attribute FrozenArray<PerformanceServerTiming> serverTiming;
};