// Source: Soft Navigations and Interaction Contentful Paint (https://wicg.github.io/soft-navigations/)
[Exposed=Window]
interface PerformanceSoftNavigation : PerformanceEntry {
    readonly attribute NavigationType navigationType;
    readonly attribute unsigned long long interactionId;
    InteractionContentfulPaint? getLargestInteractionContentfulPaint();

    [Default] object toJSON();
};

// Source: Soft Navigations and Interaction Contentful Paint (https://wicg.github.io/soft-navigations/)
PerformanceSoftNavigation includes PaintTimingMixin;