// Source: Permissions Policy (https://www.w3.org/TR/permissions-policy-1/)
dictionary PermissionsPolicyViolationReportBody : ReportBody {
  DOMString featureId;
  DOMString? sourceFile;
  long? lineNumber;
  long? columnNumber;
  DOMString disposition;
  DOMString? allowAttribute;
  DOMString? srcAttribute;
};