// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary PlaneInit {
  required BufferSource src;
  [EnforceRange] required unsigned long stride;
  [EnforceRange] required unsigned long rows;
};