// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
[Exposed=Window]
interface PluginArray {
  undefined refresh();
  readonly attribute unsigned long length;
  object? item(unsigned long index);
  object? namedItem(DOMString name);
};