// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
interface mixin PopoverTargetAttributes {
  [CEReactions, Reflect] attribute Element? popoverTargetElement;
  [CEReactions] attribute DOMString popoverTargetAction;
};