// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
interface mixin PopoverInvokerElement {
  [CEReactions, Reflect] attribute Element? popoverTargetElement;
  [CEReactions] attribute DOMString popoverTargetAction;
};