// Source: Privacy-Preserving Attribution: Level 1 (https://www.w3.org/TR/privacy-preserving-attribution/)
[SecureContext, Exposed=Window]
interface PrivateAttribution {
  readonly attribute PrivateAttributionAggregationServices aggregationServices;
};

// Source: Privacy-Preserving Attribution: Level 1 (https://www.w3.org/TR/privacy-preserving-attribution/)
[SecureContext, Exposed=Window]
partial interface PrivateAttribution {
  undefined saveImpression(PrivateAttributionImpressionOptions options);
};

// Source: Privacy-Preserving Attribution: Level 1 (https://www.w3.org/TR/privacy-preserving-attribution/)
[SecureContext, Exposed=Window]
partial interface PrivateAttribution {
  Promise<PrivateAttributionConversionResult> measureConversion(PrivateAttributionConversionOptions options);
};