// Source: Privacy-Preserving Attribution: Level 1 (https://w3c.github.io/ppa/)
[SecureContext, Exposed=Window]
interface PrivateAttributionAggregationServices {
  readonly maplike<USVString, PrivateAttributionAggregationService>;
};