// Source: Private State Token API (https://wicg.github.io/trust-token-api/)
dictionary PrivateToken {
  required TokenType type;
  required TokenVersion version;
  required OperationType operation;
  RefreshPolicy refreshPolicy = "none";
  sequence<USVString> issuers;
};