// Source: Privacy-Preserving Attribution: Level 1 (https://w3c.github.io/ppa/)
dictionary PrivateAttributionImpressionOptions {
  required unsigned long histogramIndex;
  required unsigned long filterData;
  required DOMString conversionSite;
  unsigned long lifetimeDays = 30;
};