// Source: Privacy-Preserving Attribution: Level 1 (https://www.w3.org/TR/privacy-preserving-attribution/)
dictionary PrivateAttributionImpressionOptions {
  required unsigned long histogramIndex;
  unsigned long matchValue = 0;
  sequence<USVString> conversionSites = [];
  unsigned long lifetimeDays = 30;
};