// Source: Privacy-Preserving Attribution: Level 1 (https://www.w3.org/TR/privacy-preserving-attribution/)
[SecureContext, Exposed=Window]
interface PrivateAttributionAggregationServices {
  readonly maplike<USVString, PrivateAttributionAggregationService>;
};