// Source: Privacy-Preserving Attribution: Level 1 (https://w3c.github.io/ppa/)
dictionary PrivateAttributionImpressionOptions {
  required unsigned long histogramIndex;
  unsigned long filterData = 0;
  required USVString conversionSite;
  unsigned long lifetimeDays = 30;
};