// Source: JS Self-Profiling API (https://wicg.github.io/js-self-profiling/)
dictionary ProfilerFrame {
  DOMString name;
  required unsigned long long resourceId;
  required unsigned long long line;
  required unsigned long long column;
};