// Source: Proofreader API (https://webmachinelearning.github.io/proofreader-api/)
dictionary ProofreaderCreateOptions : ProofreaderCreateCoreOptions {
    AbortSignal signal;
    CreateMonitorCallback monitor;
};