// Source: Streams Standard (https://streams.spec.whatwg.org/)
[Exposed=(Window,Worker,Worklet)]
interface ReadableStreamDefaultReader {
  constructor(ReadableStream stream);

  Promise<ReadableStreamDefaultReadResult> read();
  undefined releaseLock();
};

// Source: Streams Standard (https://streams.spec.whatwg.org/)
ReadableStreamDefaultReader includes ReadableStreamGenericReader;