// Source: Streams Standard (https://streams.spec.whatwg.org/)
[Exposed=*]
interface ReadableStreamBYOBRequest {
  readonly attribute Uint8Array? view;

  undefined respond([EnforceRange] unsigned long long bytesWritten);
  undefined respondWithNewView(ArrayBufferView view);
};