// Source: Streams Standard (https://streams.spec.whatwg.org/)
[Exposed=(Window,Worker,Worklet)]
interface ReadableStreamBYOBReader {
  constructor(ReadableStream stream);

  Promise<ReadableStreamBYOBReadResult> read(ArrayBufferView view);
  undefined releaseLock();
};

// Source: Streams Standard (https://streams.spec.whatwg.org/)
ReadableStreamBYOBReader includes ReadableStreamGenericReader;