// Source: Protected Audience (formerly FLEDGE) (https://wicg.github.io/turtledove/)
dictionary RealTimeContribution {
  required long bucket;
  required double priorityWeight;
  long latencyThreshold;
};