// Source: Protected Audience (formerly FLEDGE) (https://wicg.github.io/turtledove/)
[Exposed=InterestGroupBiddingAndScoringScriptRunnerGlobalScope]
interface RealTimeReporting {
  undefined contributeToHistogram(RealTimeContribution contribution);
};