// Source: WebTransport (https://www.w3.org/TR/webtransport/)
[ Exposed=(Window,Worker) ]
interface ReceiveStream : ReadableStream /* of Uint8Array */ {
  readonly attribute Promise<StreamAbortInfo> remoteReset;
};