// Source: WebMCP (https://webmachinelearning.github.io/webmcp/)
dictionary RegisteredTool {
  required DOMString name;
  // `title` can be exposed as a `DOMString` since it was taken in by a
  // `USVString`, meaning all unmatched surrogate processing has already been
  // done, and there's no need to do it again on tool exposure.
  DOMString title;
  required DOMString description;
  DOMString inputSchema;
  required Window window;
  required USVString origin;
  ToolAnnotations annotations;
};