// Source: [No title found for https://drafts.csswg.org/css-regions/] (https://www.w3.org/TR/css-regions-1/)
interface mixin Region {
  readonly attribute CSSOMString regionOverset;
  sequence<Range>? getRegionFlowRanges();
};