// Source: Element Capture (https://screen-share.github.io/element-capture/)
[Exposed=(Window,Worker), Serializable]
interface RestrictionTarget {
  [Exposed=Window, SecureContext] static Promise<RestrictionTarget> fromElement(Element element);
};