// Source: WebRTC 1.0: Real-Time Communication Between Browsers (https://www.w3.org/TR/webrtc/)
dictionary RTCConfiguration {
  sequence<RTCIceServer> iceServers;
  RTCIceTransportPolicy iceTransportPolicy;
  RTCBundlePolicy bundlePolicy;
  RTCRtcpMuxPolicy rtcpMuxPolicy;
  sequence<RTCCertificate> certificates;
  [EnforceRange] octet iceCandidatePoolSize = 0;
};

// Source: WebRTC Encoded Transform (https://w3c.github.io/webrtc-encoded-transform/)
// New fields in RTCConfiguration
partial dictionary RTCConfiguration {
    boolean encodedInsertableStreams = false;
};

// Source: Identity for WebRTC 1.0 (https://www.w3.org/TR/webrtc-identity/)
partial dictionary RTCConfiguration {
    DOMString peerIdentity;
};