// Source: WebRTC: Real-Time Communication in Browsers (https://www.w3.org/TR/webrtc/)
dictionary RTCIceServer {
  required (USVString or sequence<USVString>) urls;
  DOMString username;
  DOMString credential;
};