// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
[Exposed=Window]
interface RTCRtpSFrameEncryptor {
    constructor(RTCRtpSFrameEncryptorOptions options);
};

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
RTCRtpSFrameEncryptor includes SFrameEncryptorManager;