// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
[Exposed=Window]
interface RTCRtpSFrameDecryptor : EventTarget {
    constructor(SFrameTransformOptions options);
};

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
RTCRtpSFrameDecryptor includes SFrameDecryptorManager;