// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
[Exposed=Window]
interface RTCRtpSFrameDecrypter : EventTarget {
    constructor(SFrameTransformOptions options);
};

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
RTCRtpSFrameDecrypter includes SFrameDecrypterManager;