// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
[Exposed=Window]
interface RTCSFrameReceiverTransform : EventTarget {
    constructor(optional SFrameTransformOptions options = {});
};

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
RTCSFrameReceiverTransform includes SFrameDecrypterManager;