// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
[Exposed=Window]
interface RTCSFrameSenderTransform {
    constructor(optional RTCSFrameSenderTransformOptions options = {});
};

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
RTCSFrameSenderTransform includes SFrameEncrypterManager;