// Source: WebRTC Insertable Media using Streams (https://w3c.github.io/webrtc-insertable-streams/)
// New interfaces to expose JavaScript-based transforms.

// FIXME: We want to expose only in dedicated worker scopes.
[Exposed=Worker]
interface RTCTransformEvent : Event {
    readonly attribute RTCRtpScriptTransformer transformer;
};