// Source: HTML Sanitizer API (https://wicg.github.io/sanitizer-api/)
[Exposed=(Window,Worker)]
interface Sanitizer {
  constructor(optional SanitizerConfig config = {});
  SanitizerConfig get();
  SanitizerConfig getUnsafe();
};