// Source: HTML Sanitizer API (https://wicg.github.io/sanitizer-api/)
[
  Exposed=(Window),
  SecureContext
] interface Sanitizer {
  constructor(optional SanitizerConfig aConfig = {});

  DocumentFragment sanitize(SanitizerInput input);
  DOMString sanitizeToString(SanitizerInput input);

  readonly attribute SanitizerConfig config;
  static readonly attribute SanitizerConfig defaultConfig;
};