// Source: Protected Audience (formerly FLEDGE) (https://wicg.github.io/turtledove/)
dictionary ScoreAdOutput {
  required double desirability;
  double bid;
  DOMString bidCurrency;
  double incomingBidInSellerCurrency;
  boolean allowComponentAuction = false;
};