// Source: The Screen Fold API (https://www.w3.org/TR/screen-fold/)
[SecureContext, Exposed=(Window)]
interface ScreenFold : EventTarget {
  readonly attribute ScreenFoldPosture posture;
  attribute EventHandler onchange;
};