// Source: Scripting Policy (https://wicg.github.io/csp-next/scripting-policy.html)
dictionary ScriptingPolicyReportBody : ReportBody {
  DOMString     violationType;
  USVString?    violationURL;
  USVString?    violationSample;
  unsigned long lineno;
  unsigned long colno;
};