// Source: Long Animation Frames API (https://www.w3.org/TR/long-animation-frames/)
enum ScriptInvokerType {
    "classic-script",
    "module-script",
    "event-listener",
    "user-callback",
    "resolve-promise",
    "reject-promise"
};