// Source: CSSOM View Module Level 1 (https://www.w3.org/TR/cssom-view-1/)
dictionary ScrollIntoViewOptions : ScrollOptions {
  ScrollLogicalPosition block = "start";
  ScrollLogicalPosition inline = "nearest";
  ScrollIntoViewContainer container = "all";
};