// Source: Scroll-linked Animations (https://drafts.csswg.org/scroll-animations-1/)
[Exposed=Window]
interface ScrollTimeline : AnimationTimeline {
  constructor(optional ScrollTimelineOptions options = {});
  readonly attribute Element? source;
  readonly attribute ScrollDirection orientation;
  readonly attribute ScrollTimelineOffset start;
  readonly attribute ScrollTimelineOffset end;
  readonly attribute (double or ScrollTimelineAutoKeyword) timeRange;
};