// Source: Scroll-linked Animations (https://drafts.csswg.org/scroll-animations-1/)
dictionary ScrollTimelineOptions {
  Element? source;
  ScrollDirection orientation = "block";
  ScrollTimelineOffset start = "auto";
  ScrollTimelineOffset end = "auto";
  (double or ScrollTimelineAutoKeyword) timeRange = "auto";
};