// Source: Secure Payment Confirmation (https://www.w3.org/TR/secure-payment-confirmation/)
enum SecurePaymentConfirmationAvailability {
  "available",
  "unavailable-unknown-reason",
  "unavailable-feature-not-enabled",
  "unavailable-no-permission-policy",
  "unavailable-no-user-verifying-platform-authenticator",
};