// Source: Web Animations Module Level 2 (https://www.w3.org/TR/web-animations-2/)
[Exposed=Window]
interface SequenceEffect : GroupEffect {
  constructor(sequence<AnimationEffect>? children,
              optional (unrestricted double or EffectTiming) timing = {});

  SequenceEffect clone ();
};