// Source: Web Serial API (https://serial.spec.whatwg.org/)
dictionary SerialPortFilter {
  unsigned short usbVendorId;
  unsigned short usbProductId;
  BluetoothServiceUUID bluetoothServiceClassId;
};