// Source: WebSerial Standard (https://serial.spec.whatwg.org/)
dictionary SerialPortInfo {
  unsigned short usbVendorId;
  unsigned short usbProductId;
  BluetoothServiceUUID bluetoothServiceClassId;
};