// Source: Web Bluetooth (https://bluetooth.spec.whatwg.org/)
[SecureContext]
interface mixin ServiceEventHandlers {
  attribute EventHandler onserviceadded;
  attribute EventHandler onservicechanged;
  attribute EventHandler onserviceremoved;
};