// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
[Exposed=(Window,DedicatedWorker)]
interface SFrameDecrypterStream : EventTarget {
    constructor(optional SFrameTransformOptions options = {});
};

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
SFrameDecrypterStream includes GenericTransformStream;

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
SFrameDecrypterStream includes SFrameDecrypterManager;