// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
[Exposed=(Window,DedicatedWorker)]
interface SFrameDecryptorStream : EventTarget {
    constructor(SFrameTransformOptions options);
};

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
SFrameDecryptorStream includes GenericTransformStream;

// Source: WebRTC Encoded Transform (https://www.w3.org/TR/webrtc-encoded-transform/)
SFrameDecryptorStream includes SFrameDecryptorManager;