// Source: DOM Standard (https://dom.spec.whatwg.org/)
[Exposed=Window]
interface ShadowRoot : DocumentFragment {
  readonly attribute ShadowRootMode mode;
  readonly attribute boolean delegatesFocus;
  readonly attribute SlotAssignmentMode slotAssignment;
  readonly attribute boolean clonable;
  readonly attribute boolean serializable;
  readonly attribute Element host;
  attribute EventHandler onslotchange;
};

// Source: DOM Standard (https://dom.spec.whatwg.org/)
ShadowRoot includes DocumentOrShadowRoot;

// Source: HTML Standard (https://html.spec.whatwg.org/multipage/)
partial interface ShadowRoot {
  [CEReactions] undefined setHTMLUnsafe(HTMLString html);
  DOMString getHTML(optional GetHTMLOptions options = {});

  [CEReactions] attribute [LegacyNullToEmptyString] HTMLString innerHTML;
};