// Source: Shared Storage API (https://wicg.github.io/shared-storage/)
[Exposed=SharedStorageWorklet]
interface SharedStorageRunOperation : SharedStorageOperation {
  Promise<undefined> run(object data);
};