// Source: Shared Storage API (https://wicg.github.io/shared-storage/)
[
  Exposed=SharedStorageWorklet
] interface SharedStorageWorkletNavigator {};

// Source: Shared Storage API (https://wicg.github.io/shared-storage/)
SharedStorageWorkletNavigator includes NavigatorLocks;