// Source: Shared Storage API (https://wicg.github.io/shared-storage/)
[Exposed=SharedStorageWorklet, Global=SharedStorageWorklet]
interface SharedStorageWorkletGlobalScope : WorkletGlobalScope {
  undefined register(DOMString name,
                     SharedStorageOperationConstructor operationCtor);

  readonly attribute WorkletSharedStorage sharedStorage;
};