// Source: Web App Manifest (https://www.w3.org/TR/appmanifest/)
dictionary ShortcutItem {
  required USVString name;
  USVString short_name;
  USVString description;
  required USVString url;
  sequence<ManifestImageResource> icons;
};