// Source: CSS Scroll Snap Module Level 2 (https://drafts.csswg.org/css-scroll-snap-2/)
[Exposed=Window]
interface SnapTargetList {
    readonly attribute SnapTargetArray x;
    readonly attribute SnapTargetArray y;
};