// Source: Web Speech API (https://webaudio.github.io/web-speech-api/)
enum SpeechRecognitionMode {
    "ondevice-preferred", // On-device speech recognition if available, otherwise use Cloud speech recognition as a fallback.
    "ondevice-only", // On-device speech recognition only. Returns an error if on-device speech recognition is not available.
    "cloud-only", // Cloud speech recognition only.
};