// Source: Web Speech API (https://webaudio.github.io/web-speech-api/)
// Item in N-best list
[SecureContext, Exposed=Window]
interface SpeechRecognitionAlternative {
    readonly attribute DOMString transcript;
    readonly attribute float confidence;
};