// Source: CSS View Transitions Module Level 2 (https://drafts.csswg.org/css-view-transitions-2/)
dictionary StartViewTransitionOptions {
  UpdateCallback? update = null;
  sequence<DOMString>? types = null;
};