// Source: Web Audio API 1.1 (https://www.w3.org/TR/webaudio/)
[Exposed=Window]
interface StereoPannerNode : AudioNode {
    constructor (BaseAudioContext context, optional StereoPannerOptions options = {});
    readonly attribute AudioParam pan;
};