// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
[Exposed=Window]
interface SVGAnimatedString {
           attribute (DOMString or TrustedScriptURL) baseVal;
  readonly attribute DOMString animVal;
};