// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
[Exposed=Window]
interface SVGAElement : SVGGraphicsElement {
  [Reflect, SameObject] readonly attribute SVGAnimatedString target;
  [Reflect] attribute DOMString download;
  [Reflect] attribute USVString ping;
  [Reflect] attribute DOMString rel;
  [Reflect="rel", SameObject, PutForwards=value] readonly attribute DOMTokenList relList;

  attribute DOMString referrerPolicy;
};

// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
SVGAElement includes SVGURIReference;

// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
SVGAElement includes HyperlinkElementUtils;