// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG11/)
[Exposed=Window]
interface SVGAnimatedEnumeration {
           attribute unsigned short baseVal;
  readonly attribute unsigned short animVal;
};