// Source: SVG Animations (https://svgwg.org/specs/animations/)
interface SVGMPathElement : SVGElement {
};

// Source: SVG Animations (https://svgwg.org/specs/animations/)
SVGMPathElement includes SVGURIReference;