// Source: SVG Markers (https://www.w3.org/TR/svg-markers/)
interface SVGMarkerInstance {
  readonly attribute SVGMarkerElement element;
  readonly attribute float position;
  readonly attribute DOMPointReadOnly point;
  readonly attribute float angle;
};