// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
[Exposed=Window]
interface SVGPathElement : SVGGeometryElement {
};

// Source: SVG Markers (https://www.w3.org/TR/svg-markers/)
SVGPathElement includes SVGMarkableElement;