// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
[Exposed=Window]
interface SVGPolylineElement : SVGGeometryElement {
};

// Source: SVG Markers (https://www.w3.org/TR/svg-markers/)
SVGPolylineElement includes SVGMarkableElement;

// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
SVGPolylineElement includes SVGAnimatedPoints;