// Source: SVG Paths (https://www.w3.org/TR/svg-paths/)
[Exposed=Window]
interface SVGPathElement : SVGGeometryElement {

  readonly attribute SVGAnimatedNumber pathLength;

  float getTotalLength();
  DOMPoint getPointAtLength(float distance);
  SVGPathSegment? getPathSegmentAtLength(float distance);
};

// Source: SVG Paths (https://www.w3.org/TR/svg-paths/)
SVGPathElement includes SVGPathData;