// Source: SVG Animations (https://svgwg.org/specs/animations/)
partial interface SVGSVGElement {
  void pauseAnimations();
  void unpauseAnimations();
  boolean animationsPaused();
  float getCurrentTime();
  void setCurrentTime(float seconds);
};