// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
[Exposed=Window]
interface SVGSVGElement : SVGGraphicsElement {

  [SameObject] readonly attribute SVGAnimatedLength x;
  [SameObject] readonly attribute SVGAnimatedLength y;
  [SameObject] readonly attribute SVGAnimatedLength width;
  [SameObject] readonly attribute SVGAnimatedLength height;

  attribute float currentScale;
  [SameObject] readonly attribute SVGPoint currentTranslate;

  NodeList getIntersectionList(SVGRect rect, SVGElement? referenceElement);
  NodeList getEnclosureList(SVGRect rect, SVGElement? referenceElement);
  boolean checkIntersection(SVGElement element, SVGRect rect);
  boolean checkEnclosure(SVGElement element, SVGRect rect);

  undefined deselectAll();

  [NewObject] SVGNumber createSVGNumber();
  [NewObject] SVGLength createSVGLength();
  [NewObject] SVGAngle createSVGAngle();
  [NewObject] SVGPoint createSVGPoint();
  [NewObject] SVGMatrix createSVGMatrix();
  [NewObject] SVGRect createSVGRect();
  [NewObject] SVGTransform createSVGTransform();
  [NewObject] SVGTransform createSVGTransformFromMatrix(optional DOMMatrix2DInit matrix = {});

  Element? getElementById(DOMString elementId);

  // Deprecated methods that have no effect when called,
  // but which are kept for compatibility reasons.
  unsigned long suspendRedraw(unsigned long maxWaitMilliseconds);
  undefined unsuspendRedraw(unsigned long suspendHandleID);
  undefined unsuspendRedrawAll();
  undefined forceRedraw();
};

// Source: SVG Animations (https://svgwg.org/specs/animations/)
partial interface SVGSVGElement {
  undefined pauseAnimations();
  undefined unpauseAnimations();
  boolean animationsPaused();
  float getCurrentTime();
  undefined setCurrentTime(float seconds);
};

// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
SVGSVGElement includes SVGFitToViewBox;

// Source: Scalable Vector Graphics (SVG) 2 (https://www.w3.org/TR/SVG2/)
SVGSVGElement includes WindowEventHandlers;