// Source: Direct Sockets API (https://wicg.github.io/direct-sockets/)
[Exposed=(Window,Worker), SecureContext]
interface TCPSocket {
  constructor(DOMString remoteAddress,
              unsigned short remotePort,
              optional TCPSocketOptions options = {});

  readonly attribute Promise<TCPSocketOpenInfo> opened;
  readonly attribute Promise<undefined> closed;

  Promise<undefined> close();
};