// Source: Direct Sockets API (https://wicg.github.io/direct-sockets/)
dictionary TCPSocketOptions {
  [EnforceRange] unsigned long sendBufferSize;
  [EnforceRange] unsigned long receiveBufferSize;

  boolean noDelay = false;
  [EnforceRange] unsigned long keepAliveDelay;

  SocketDnsQueryType dnsQueryType;
};