// Source: Accelerated Text Detection in Images (https://wicg.github.io/shape-detection-api/text.html)
dictionary TextDetectorCreateOptions {
    AbortSignal signal;
    sequence<DOMString> languages;
};