// Source: EditContext API (https://www.w3.org/TR/edit-context/)
[Exposed=Window]
interface TextFormat {
    constructor(optional TextFormatInit options = {});
    readonly attribute unsigned long rangeStart;
    readonly attribute unsigned long rangeEnd;
    readonly attribute DOMString textColor;
    readonly attribute DOMString backgroundColor;
    readonly attribute DOMString underlineStyle;
    readonly attribute DOMString underlineThickness;
    readonly attribute DOMString underlineColor;
};