// Source: Media Source Extensions™ (https://www.w3.org/TR/media-source-2/)
[Exposed=(Window,DedicatedWorker)]
partial interface TextTrack {
    readonly        attribute SourceBuffer? sourceBuffer;
};