// Source: Encoding Standard (https://www.w3.org/TR/encoding/)
[Exposed=*]
interface TextDecoderStream {
  constructor(optional DOMString label = "utf-8", optional TextDecoderOptions options = {});
};

// Source: Encoding Standard (https://www.w3.org/TR/encoding/)
TextDecoderStream includes TextDecoderCommon;

// Source: Encoding Standard (https://www.w3.org/TR/encoding/)
TextDecoderStream includes GenericTransformStream;