// Source: Encoding Standard (https://www.w3.org/TR/encoding/)
interface mixin TextDecoderCommon {
  readonly attribute DOMString encoding;
  readonly attribute boolean fatal;
  readonly attribute boolean ignoreBOM;
};