// Source: requestStorageAccessFor API (https://privacycg.github.io/requestStorageAccessForOrigin/)
dictionary TopLevelStorageAccessPermissionDescriptor : PermissionDescriptor {
    USVString requestedOrigin = "";
};