// Source: Translator and Language Detector APIs (https://webmachinelearning.github.io/translation-api/)
dictionary TranslatorCreateCoreOptions {
  required DOMString sourceLanguage;
  required DOMString targetLanguage;
};