// Source: Trusted Types (https://w3c.github.io/trusted-types/dist/spec/)
dictionary TrustedTypePolicyOptions {
   CreateHTMLCallback? createHTML;
   CreateScriptCallback? createScript;
   CreateScriptURLCallback? createScriptURL;
};