// Source: User-Agent Client Hints (https://wicg.github.io/ua-client-hints/)
dictionary UADataValues {
  DOMString architecture;
  DOMString bitness;
  DOMString model;
  DOMString platformVersion;
  DOMString uaFullVersion;
};