// Source: Direct Sockets API (https://wicg.github.io/direct-sockets/)
dictionary UDPMessage {
  BufferSource data;
  DOMString remoteAddress;
  unsigned short remotePort;
  SocketDnsQueryType dnsQueryType;
};