// Source: Direct Sockets API (https://wicg.github.io/direct-sockets/)
[Exposed=(Window,Worker), SecureContext]
interface UDPSocket {
  constructor(optional UDPSocketOptions options = {});

  readonly attribute Promise<UDPSocketOpenInfo> opened;
  readonly attribute Promise<undefined> closed;

  Promise<undefined> close();
};