// Source: Direct Sockets API (https://wicg.github.io/direct-sockets/)
dictionary UDPSocketOptions {
  DOMString remoteAddress;
  [EnforceRange] unsigned short remotePort;

  DOMString localAddress;
  [EnforceRange] unsigned short localPort;

  [EnforceRange] unsigned long sendBufferSize;
  [EnforceRange] unsigned long receiveBufferSize;

  SocketDnsQueryType dnsQueryType;
  boolean ipv6Only;
};