// Source: UI Events (https://www.w3.org/TR/uievents/)
dictionary UIEventInit : EventInit {
  Window? view = null;
  long detail = 0;
};

// Source: UI Events (https://www.w3.org/TR/uievents/)
partial dictionary UIEventInit {
  unsigned long which = 0;
};