// Source: WebUSB API (https://usb.spec.whatwg.org/)
[
  Exposed=(Worker,Window),
  SecureContext
]
interface USBIsochronousInTransferPacket {
  constructor(USBTransferStatus status, optional DataView? data);
  readonly attribute DataView? data;
  readonly attribute USBTransferStatus status;
};