// Source: Web Bluetooth (https://bluetooth.spec.whatwg.org/)
[
  Exposed=Window,
  SecureContext
]
interface ValueEvent : Event {
  constructor(DOMString type, optional ValueEventInit initDict = {});
  readonly attribute any value;
};