// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary VideoEncoderEncodeOptions {
  boolean keyFrame = false;
};

// Source: VP9 WebCodecs Registration (https://www.w3.org/TR/webcodecs-vp9-codec-registration/)
partial dictionary VideoEncoderEncodeOptions {
  VideoEncoderEncodeOptionsForVp9 vp9;
};