// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary VideoFrameRect {
  [EnforceRange] required unsigned long left;
  [EnforceRange] required unsigned long top;
  [EnforceRange] required unsigned long width;
  [EnforceRange] required unsigned long height;
};