// Source: WebCodecs (https://wicg.github.io/web-codecs/)
dictionary VideoEncoderConfig {
  required DOMString codec;
  unsigned long long bitrate;
  required unsigned long cropWidth;
  required unsigned long cropHeight;
  unsigned long displayWidth;
  unsigned long displayHeight;

  AvcEncoderConfig avc;
};