// Source: WebCodecs (https://www.w3.org/TR/webcodecs/)
dictionary VideoFrameInit {
  unsigned long long duration;  // microseconds
  long long timestamp;          // microseconds
  AlphaOption alpha = "keep";
};