// Source: WebCodecs (https://wicg.github.io/web-codecs/)
[Exposed=Window]
interface VideoTrackReader {
  constructor(MediaStreamTrack track);

  readonly attribute VideoTrackReaderState readyState;
  attribute EventHandler onended;

  undefined start(VideoFrameOutputCallback callback);
  undefined stop();
};