// Source: Web Audio API 1.1 (https://www.w3.org/TR/webaudio-1.1/)
[Exposed=Window]
interface WaveShaperNode : AudioNode {
    constructor (BaseAudioContext context, optional WaveShaperOptions options = {});
    attribute Float32Array? curve;
    attribute OverSampleType oversample;
};