// Source: WebGL WEBGL_depth_texture Khronos Ratified Extension Specification (https://www.khronos.org/registry/webgl/extensions/WEBGL_depth_texture/)
[LegacyNoInterfaceObject]
interface WEBGL_depth_texture {
  const GLenum UNSIGNED_INT_24_8_WEBGL = 0x84FA;
};