// Source: WebTransport (https://w3c.github.io/webtransport/)
[Exposed=(Window,Worker)]
interface WebTransport {
  constructor(USVString url, optional WebTransportOptions options = {});

  Promise<WebTransportStats> getStats();
  readonly attribute WebTransportState state;
  readonly attribute Promise<undefined> ready;
  readonly attribute Promise<WebTransportCloseInfo> closed;
  undefined close(optional WebTransportCloseInfo closeInfo = {});
  attribute EventHandler onstatechange;
};

// Source: WebTransport (https://w3c.github.io/webtransport/)
WebTransport includes UnidirectionalStreamsTransport;

// Source: WebTransport (https://w3c.github.io/webtransport/)
WebTransport includes BidirectionalStreamsTransport;

// Source: WebTransport (https://w3c.github.io/webtransport/)
WebTransport includes DatagramTransport;