// Source: Shared Storage API (https://wicg.github.io/shared-storage/)
[Exposed=(Window)]
interface WindowSharedStorage : SharedStorage {
  Promise<SharedStorageResponse> selectURL(DOMString name,
                               sequence<SharedStorageUrlWithMetadata> urls,
                               optional SharedStorageRunOperationMethodOptions options = {});
  Promise<any> run(DOMString name,
                   optional SharedStorageRunOperationMethodOptions options = {});

  Promise<SharedStorageWorklet> createWorklet(USVString moduleURL, optional WorkletOptions options = {});

  readonly attribute SharedStorageWorklet worklet;
};