// Source: Portals (https://wicg.github.io/portals/)
partial interface mixin WindowEventHandlers {
    attribute EventHandler onportalactivate;
};

// Source: Gamepad (https://www.w3.org/TR/gamepad/)
partial interface mixin WindowEventHandlers {
  attribute EventHandler ongamepadconnected;
  attribute EventHandler ongamepaddisconnected;
};