// Source: Fetch Standard (https://fetch.spec.whatwg.org/)
partial interface mixin WindowOrWorkerGlobalScope {
  [NewObject] Promise<Response> fetch(RequestInfo input, optional RequestInit init = {});
};

// Source: Trusted Types (https://w3c.github.io/webappsec-trusted-types/dist/spec/)
partial interface mixin WindowOrWorkerGlobalScope {
  readonly attribute TrustedTypePolicyFactory trustedTypes;
};

// Source: Origin Policy (https://wicg.github.io/origin-policy/)
partial interface mixin WindowOrWorkerGlobalScope {
  readonly attribute FrozenArray<DOMString> originPolicyIds;
};

// Source: Prioritized Task Scheduling (https://wicg.github.io/scheduling-apis/)
partial interface mixin WindowOrWorkerGlobalScope {
  readonly attribute Scheduler scheduler;
};

// Source: High Resolution Time (https://www.w3.org/TR/hr-time-3/)
partial interface mixin WindowOrWorkerGlobalScope {
  [Replaceable] readonly attribute Performance performance;
};

// Source: Indexed Database API 3.0 (https://www.w3.org/TR/IndexedDB-3/)
partial interface mixin WindowOrWorkerGlobalScope {
  [SameObject] readonly attribute IDBFactory indexedDB;
};

// Source: Service Workers Nightly (https://www.w3.org/TR/service-workers-1/)
partial interface mixin WindowOrWorkerGlobalScope {
  [SecureContext, SameObject] readonly attribute CacheStorage caches;
};

// Source: Web Cryptography API (https://www.w3.org/TR/WebCryptoAPI/)
partial interface mixin WindowOrWorkerGlobalScope {
  [SameObject] readonly attribute Crypto crypto;
};