// Source: Writing Assistance APIs (https://webmachinelearning.github.io/writing-assistance-apis/)
dictionary WriterCreateOptions : WriterCreateCoreOptions {
  AbortSignal signal;
  CreateMonitorCallback monitor;

  DOMString sharedContext;
};