// Source: WebXR Body Tracking Module - Level 1 (https://immersive-web.github.io/body-tracking/)
[Exposed=Window]
interface XRBody {
    iterable<XRBodyJoint, XRBodySpace>;

    readonly attribute unsigned long size;
    XRBodySpace get(XRBodyJoint key);
};