// Source: WebXR Depth Sensing Module (https://immersive-web.github.io/depth-sensing/)
dictionary XRDepthStateInit {
  required sequence<XRDepthUsage> usagePreference;
  required sequence<XRDepthDataFormat> dataFormatPreference;
};