// Source: WebXR Device API (https://www.w3.org/TR/webxr/)
dictionary XRInputSourcesChangeEventInit : EventInit {
  required XRSession session;
  required sequence<XRInputSource> added;
  required sequence<XRInputSource> removed;

};