// Source: CSS Typed OM Level 1 (https://www.w3.org/TR/css-typed-om-1/)
[Exposed=(Window, Worker, PaintWorklet, LayoutWorklet)]
interface CSSColorValue : CSSStyleValue {
    readonly attribute CSSKeywordValue colorSpace;
    CSSColorValue to(CSSKeywordish colorSpace);
    [Exposed=Window] static CSSColorValue parse(USVString cssText);
};