// Source: WebGL OES_texture_float Khronos Ratified Extension Specification (https://www.khronos.org/registry/webgl/extensions/OES_texture_float/)
[Exposed=(Window,Worker), LegacyNoInterfaceObject]
interface OES_texture_float { };