name: "@webref/css: Prepare release PR if needed"

on:
  push:
    branches:
      - master
    paths:
      - 'ed/css/**'
      - 'ed/csspatches/**'
      - 'packages/css/**'
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x

    - name: Checkout webref
      uses: actions/checkout@v2

    - name: Prepare new release
      run: |
        npm ci
        npm run prepare

    - name: Test new release
      run: npm test

    - name: Prepare a pre-release pull request if needed
      run: node tools/prepare-release.js css
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}